### ISSUE TITLE
"Error: <g> attribute transform: Trailing garbage" with amcharts 4.2.4 

### ISSUE THREAD

**Issue by jochenjonc** [amcharts/amcharts4#1101]
After updating to amcharts 4.2.4 I get the following error in the browers developer console:

Error: <g> attribute transform: Trailing garbage

I made an example on stackblitz so you can see my code and de bug: https://stackblitz.com/edit/angular-amcharts-dateaxis-redraw-bug

**Comment by yncki** [comment]
same on current version on cdn

first load with dataSource.url works
second to refresh - changing dataSource.url 
.dataSource.load(); FAILS

'https://www.amcharts.com/lib/4/core.js'
'https://www.amcharts.com/lib/4/charts.js'
'https://www.amcharts.com/lib/4/themes/animated.js'
'https://www.amcharts.com/lib/4/themes/kelly.js'
'https://www.amcharts.com/lib/4/lang/pl_PL.js'

**Comment by develar** [comment]
Nothing helps — various invalidate methods, setting rotation to 0. It seems the only solution to dispose the whole chart and create it again...

**Comment by ronbanks** [comment]
here is a [codepen](https://codepen.io/reb777/pen/exWyYv), even if you update with the same data, it breaks.

**Comment by ronbanks** [comment]
Issue seems to be perpetuated in 4.2.5? Have you guys ever heard of unit testing, maybe this product should be returned to `beta` status and the clock rolled back on paid support.

**Comment by martynasma** [comment]
Sorry folks. We slipped. Fix is coming.

![tenor](https://user-images.githubusercontent.com/1458520/54764895-3e92d800-4c01-11e9-9b22-31710c95e382.gif)

**Comment by martynasma** [comment]
Fixed in [4.2.6].

Once again, sorry everyone.

**Comment by aleksander351** [comment]
Still a problem:
Error: <g> attribute transform: Trailing garbage, "translate(27,-Infinity)".

when calling:
am4core.create(someId, am4charts.XYChart);

version: "@amcharts/amcharts4": "4.10.39",
