### ISSUE TITLE
Error: EventDispatcher is disposed when removing top stacked series

### ISSUE THREAD

**Issue by lucianholt97** [amcharts/amcharts4#1337]
I'm having a very strange issue when dynamically adding and removing series and updating the data of the chart at the same time.
**[This pen](https://codepen.io/lucianholt/pen/RmBByJ)** shows, that when you remove the top series and then update the data of the chart, you get the error: `EventDispatcher is disposed`
However, when commenting out line 180 _or_ 181, the error disappears but I still need to update the data somehow.
Additionally (and that's strange) when I do the same with the bottom stacked series, it works fine.

I am guessing that there are async calculations in the background which interfere with each other, but I couldn't figure out how to solve it or whether it's a bug or not.

I would really appreciate your help on this issue!
Thank's in advance!

https://codepen.io/lucianholt/pen/RmBByJ

**Comment by martynasma** [comment]
Fixed in [4.4.10](https://github.com/amcharts/amcharts4/releases/tag/4.4.10).

## [4.4.10] - 2019-05-28

### Fixed
- Disposing top-most stacked series was causing a JS error.
- If `TreeMap` top level had one node only, zoom-out button was not shown after drill-down.
- Bullets were not shown on series on initial render if no animated theme was used (since last release only).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by killroy42** [comment]
I still get this error on version 4.9.0. Simple doing a `chart.series.clear()` throws the error.
