### ISSUE TITLE
timezoneOffset is ignored if dateAxis.baseInterval.timeUnit is not set to 'minute'

### ISSUE THREAD

**Issue by eTingleff** [amcharts/amcharts4#1632]
I'm charting data with an XYChart and one or more LineSeries on version 4.5.15.
The data I'm charting uses dates in Unix millisecond timestamps and each datapoint represents a day's worth of data averaged out.

When I use the following DateAxis configuration, timezoneOffset is ignored:

`dateAxis.dateFormatter.inputDateFormat = 'x';`
`dateAxis.dateFormatter.timezoneOffset = <utcOffsetMinutes>;`
`dateAxis.baseInterval = { timeUnit: 'day', count: 1 };`

but when I use the following DateAxis configuration, timezoneOffset works as expected:

`dateAxis.dateFormatter.inputDateFormat = 'x';`
`dateAxis.dateFormatter.timezoneOffset = <utcOffsetMinutes>;`
`dateAxis.baseInterval = { timeUnit: 'minute', count: 1440 };`

The only other baseInterval variation I tried that was equal to one day was:

`
dateAxis.baseInterval = { timeUnit: 'hours', count: 24 }; 
`

and the timezoneOffset was also ignored.

I created a [codepen](https://codepen.io/eTingz/pen/OJLxQXX) to demonstrate.
Both charts are using the same data and timezoneOffset (UTC +8). 
chartA (on top) is using the baseInterval { timeUnit: 'day', count: 1 } and chartB (bottom) is using the baseInterval { timeUnit: 'minute', count: 1440 }

**Comment by martynasma** [comment]
How should time zone offsetting work in a daily data?

Daily data means you have one data point per day.

Say if you have a data point for Jan 1st and Jan 2nd. What would the chart show with the offset of 1440?

Dec 31st and Jan 1?

**Comment by eTingleff** [comment]
If the date provided is as precise as milliseconds, my assumption was that the time zone offset would still be applied.

> Say if you have a data point for Jan 1st and Jan 2nd. What would the chart show with the offset of 1440?

> Dec 31st and Jan 1?

If the milliseconds time stamp provided for the dates in the desired time zone landed on Dec 31 and Jan 1, then yes, they would show those dates.

To be clear, I have achieved the desired functionality by using a base interval of { timeUnit: 'minute', count: 1440 }

Using the dataset in the codepen I linked to as an example - each millisecond time stamp date in the series is the middle of a day in UTC +8.  

The last date in the series is 1567483200000 or,
In UTC: September 3, 2019 4:00:00 (am) UTC
**Target time zone**: September 3, 2019 12:00:00 (pm) UTC +8
Browser time zone: September 2, 2019 9:00:00 (pm) UTC -7

I set dateAxis.dateFormatter.timeZoneOffset = -480; 

If dateAxis.baseInterval is set to { timeUnit: 'day', count: 1 }, the above offset is ignored and the chart uses the browser detected time zone, which for me is UTC -7 so the day ends up being displayed as September 2.

If dateAxis.baseInterval is set to { timeUnit: 'minute', count: 1440 }, the above offset is not ignored and the day date ends up being displayed in the target time zone, September 3

**Comment by martynasma** [comment]
Important thing to note is that time zone offset does not affect how dates are parsed or perceived by the chart. It's only used when formatting date/time labels.

This is why it does not make a lot of sense to me when labels are dates, since in that case timestamps are already "rounded" to the full day.

**Comment by eTingleff** [comment]
> Important thing to note is that time zone offset does not affect how dates are parsed or perceived by the chart. It's only used when formatting date/time labels.

The labels are are precisely what I am concerned with for my use case.

> This is why it does not make a lot of sense to me when labels are dates, since in that case timestamps are already "rounded" to the full day.

Yes they are rounded to the full day, but _which_ full day as presented by the labels is important for my use case.  I need the labels to represent the date in a specific time zone and independent of any given browser's local time zone.

Going back to my [example on codepen](https://codepen.io/eTingz/pen/OJLxQXX), what I need for my use case is the chart on the bottom - for those data points to have date labels which represent the dates from which they were collected in one specific time zone, viewed from anywhere in the world.

As I was writing this, I realized that depending on where you are located, the two charts in the codepen may appear identical... whoops (I feel silly now because I created this issue for this very reason).  

For me, they are not identical.

![image](https://user-images.githubusercontent.com/24258016/64403502-9f865f00-d02d-11e9-822b-d460766f23de.png)

Apart from my own lapse in thinking there, sorry for any other lack of clarity on my part.

**Comment by martynasma** [comment]
Gah, this is blowing my mind a bit :)

I'll need to give it some more thinking. Will keep you posted.

**Comment by klmntoth** [comment]
the property called timezoneOffset (with lower case z) by the way

**Comment by eTingleff** [comment]
> the property called timezoneOffset (with lower case z) by the way

@klmntoth Thank you for pointing this out.

Just so it's clear, I committed the typo "timeZoneOffset" in the title/comments of this issue, but not in my project where initially noticed the inconsistent behavior.  

I created this issue on Sept 5 and the code pen I created was using version 4.5.16

I am looking at it now in codepen with the latest release 4.6.1 and the changes made since 4.5.16 seems to have changed the behavior somewhat.

Other specifics aside, setting `dateAxis.dateFormatter.timezoneOffset` still only seems to function properly when `dateAxis.baseInterval = { timeUnit: 'minute', count: <number> }`

In the latest release, using a `dateAxis.baseInterval.timeUnit` of something other than minute in conjunction with a timezoneOffset still results in the timezoneOffset being ignored but also causes a discrepancy between stroke lines and the bullet circles that are plotted.  

Again, please note that if you view the codepen in a timezone that is +/-12 hours from Australia/Perth time the two charts may appear identical.  I am viewing it from UTC -07 which puts me 15 hours behind Aus/Perth.  This is important because each data point is at noon in Aus/Perth time - meaning the calendar date is different 

Here, is the new image example of viewing the codepen from UTC -07:

![Annotation 2019-09-19 161042](https://user-images.githubusercontent.com/24258016/65287431-17598c80-daf8-11e9-925d-513d17b49a02.jpg)

Recap:
The data for both charts is identical - each data point has a millisecond time stamp date value that lands on 12:00:00 UTC +08, both have
`dateAxis.dateFormatter.timezoneOffset = -480`,

the chart on top has 
`dateAxis.baseInterval = { timeUnit: 'day', count: 1 }`

and the chart on bottom has
`dateAxis.baseInterval = { timeUnit: 'minute', count: 1440 }`

**Comment by martynasma** [comment]
Fixed in [4.6.2](https://github.com/amcharts/amcharts4/releases/tag/4.6.2).

## [4.6.2] - 2019-09-25

### Added
- New plugin: [OverlapBuster](https://www.amcharts.com/docs/v4/tutorials/plugin-overlap-buster/). Allows automatically "exploding" overlapping items such as bullets or markers for easier access to them.
- New property: `maxZoomCount` on `Component`. Use it to limit how many items such as categories or base intervals on axes can be shown at the same time.
- Added `riseFromOpenState`, `riseFromPreviousState`, `dropFromOpenState`, and `dropFromPreviousState` setters to `ColumnSeries`. You can use them to set states to `undefined` if you don't want them to be used.
- A possibility to make "fixed" `ForceDirectedTree` nodes added (via `dataFields.fixed`). Also it is possible to set `x` and `y` of such nodes using `series.nodes.template.propertyField.x` and `y`. [More info](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Fixed_nodes).

### Changed
- Removed "GIF" option from the Export menu. Browsers don't know how to convert canvas to GIF, so it was falling back to exporting as PNG, making GIF option redundant.

### Fixed
- If chart's data source was initialized (which would happen by only accessing chart's `dataSource` property) and its `url` was not set, it was still trying to load and resulting in error.
- Formatting number with "b" modifier, was causing all numbers up to 1024 become zero.
- `ColorSet` with default (no) theme was generating colors from second in the list from `4.6.1`.
- Bullet positions were incorrect on `ValueAxis` with `baseValue` set to other than zero.
- Bullet positions with `DateAxis` could be incorrect in some cases.
- Title position of a cloned Axis was nor being positioned properly.
- Cursor was flickering if axis of a cursor had some padding set.
- Tooltip position of `MapImage` elements with `nonScaling = true` could be incorrect in some specific cases.
- Vertical axis break's fill might get out of sync with break lines if the width of a break was small.
- `RadarCursor` could show incorrect label if the chart had `CategoryAxis` with only 3 categories.
- Series was not redrawing properly if its axis range value changed.
- `PieChart` could show some labels out of chart area in some specific cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by angelnikolov** [comment]
@martynasma Any idea if this was really fixed? I am still reproducing the exact same behaviour. Also, the codepen itself is still showing the same issue (it points to https://www.amcharts.com/lib/4/charts.js which I assume is latest). Thanks in advance!

**Comment by jawaff** [comment]
@martynasma I'm still seeing some issues with the baseInterval and timezoneOffset as well. I see in the change that that timezoneOffset was previously affecting DateAxis labels and I might still be seeing that problem.

This is the part of my configuration that breaks things:
```javascript
dateAxis.baseInterval = {timeUnit: 'second', count: 1440};
chart.dateFormatter.timezoneOffset = 480;
```

Everything works just fine (using the local timezone) when I remove that part of the configuration. When the baseInterval and timezoneOffset are set, then I get the below graph.

![am4charts](https://user-images.githubusercontent.com/2895324/73113342-301fe780-3ec8-11ea-9470-f055c111a87c.PNG)

**Comment by martynasma** [comment]
@jawaff Could you post your whole chart?

**Comment by jawaff** [comment]
@martynasma I tried extracting my chart and putting it into a codepen. It might be slightly different, but it looks like the `chart.dateFormatter.timezoneOffset` still causes problems. I might be missing something I suppose, but thanks for taking a look.

https://codepen.io/jawaff/pen/abzxwbB

**Comment by zeroin** [comment]
Indeed, things got out of control after the fix if data is not daily. Working on this at the moment.

**Comment by zeroin** [comment]
OK, so since 4.8.5 we did some changes regarding timezoneOffset:
- Reverted old behavior of `DateFormatter.timezoneOffset`, because the fix introduced in 4.8.3 was not correct.

- `timezoneOffset` property added to DateAxis. Us it instead of `DateFormatter.timezoneOffset` if your dates are timestamps in your data and you want the chart to display the same dates no matter at which timezone the chart viewer is.

**Comment by jawaff** [comment]
@zeroin Rock n' roll! I don't quite get what you mean in your second bullet point there though. Could you elaborate on that a bit? It looks like setting the `DateFormatter.timezoneOffset` is currently working as I expected (I checked the codepen project I setup earlier), so what is the `DateAxis.timezoneOffset` meant for? Does the `DateAxis.timezoneOffset` allow for different charts to be in different timezones? Was that the intention?

**Comment by zeroin** [comment]
The thing is that dateFormatter.timezoneOffset only affects how the dates are formatted. So with baseInterval being < "day" it works fine. But with baseInterval "day" the result will be incorrect as Date axis does rounding, adding dates and so the result might be different, as the grid lines might appear at incorrect positions and some other issues might occur. So the correct approach would be using dateAxis.timeZoneOffset all the time and do not set any timezoneOffset on DateFormatter.

**Comment by jawaff** [comment]
@zeroin Thanks, I get it now. You might want to add a note to the documentation about that or deprecate the `DateFormatter.timezoneOffset`. Keep up the good work.

**Comment by jawaff** [comment]
@zeroin I'm seeing another weird thing with the DateAxis.timezoneOffset and it doesn't look like it's happening for the DateFormatter.timezoneOffset. Essentially if I set `DateAxis.timezoneOffset = 0;` (which I expect to mean UTC), then the local timezone is used instead.

My Javascript code is currently just converting a timezone offset and setting the variable. I'm literally just doing something like this `dateAxis.timezoneOffset = theTimezoneOffset * -60;`.

I modified my codepen project to show this issue (note that both graphs probably should not be displaying the timestamps in the same timezone):
https://codepen.io/jawaff/pen/abzxwbB

**Comment by jawaff** [comment]
@zeroin I know you guys already have people using the timezoneOffset properties, but it's really strange to me that they're in minutes and negated. For example, the timezoneOffset for GMT-8 is 480 and for GMT+8 is -480. I won't ask you guys to change it, but it's not obvious what values are valid when you check the documentation. I had to find some examples online to figure out what values are valid. Future users may appreciate some additional documentation for that property.

**Comment by zeroin** [comment]
You are right both about 0, I will fix this - thank you for noticing!

As for the minutes - it's a normal practice (some countries have non-equal hour offsets). 
Same for the negative/positive values. Try creating a Date and get `timezoneOffset`:
```
let d = new Date()
console.log(d.getTimezoneOffset())
```

if you are in +X timezone, you will get negative value and positive value if you are in -X timezone. So we follow the same rule here.

**Comment by zeroin** [comment]
`dateAxis.timezoneOffset = 0` should work fine since 4.8.6

**Comment by rathoddhruv** [comment]
@zeroin @jawaff @eTingleff and all others thank you for this conversation it really helps me.
I'm using 4.9.34

**Target time zone**: March 9, 2019 to March 11, 2019 (UTC-6 America/Regina)
**Browser time zone**: March 9, 2019 to March 11, 2019 (UTC-6 or 7 America/Calgory bcs of day light saving)
![image](https://user-images.githubusercontent.com/9565923/91615474-e8bb7700-e940-11ea-8549-ad896c9b5c39.png)


using offset everything show perfectly from march 9 to 2019-03-10T01:00-07:00 after this hour America/Calgary timezone change from UTC-7 to UTC-6 ,so dateAxis.timezoneOffset goes to 420 to 360, but for target timezone America/Regina UTC-6 remain the same.

bcs there is no 2 AM on 10th march in America/Calgary i cant see this hour in a chart too. 

![image](https://user-images.githubusercontent.com/9565923/91616156-6633b700-e942-11ea-8e4f-f4155994079d.png)


Any suggestion?
thank you
