### ISSUE TITLE
Handle overflowing nodes in force-directed-graph gracefully.

### ISSUE THREAD

**Issue by brecriffs** [amcharts/amcharts4#1713]
It would be great to have the force-directed-graph handle overflowing nodes gracefully. Perhaps an option to have a boundary that nodes bounce off would be useful. Also, other charts implement zoom in/out features. In the case that there are many nodes, maybe this chart type could benefit from that as well. 

I am currently manually scaling down the node widths and link lengths based on the number of nodes. This is an imperfect solution but seems to work. Having this be automated would be highly useful I think. Perhaps, as nodes breach the boundary of the chart, scale everything down by a factor of 'x'.

**Comment by martynasma** [comment]
Fixed in [4.10.0](https://github.com/amcharts/amcharts4/releases/tag/4.10.0).

## [4.10.0] - 2020-09-01

### Added
- New `LineSeries` property: `smoothing` (`"bezier"` (default), `"monotoneX"`, and `"monotoneY"`) - indicates algorithm to use for smoothing the lines. Monotone algos are better suited for irregularly-spaced data. [More info](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm).
- `ForcedDirectedTree`: new property `zoomable` (default: `false`). If set to `true`, the chart will be zoomable/draggable using mouse, touch, or API. [More information](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming).
- `ForcedDirectedTree`: zoom related properties added. `mouseWheelBehavior` (`"zoom"`, `"none"`) - controls what happens when mouse wheel is used over chart; `zoomStep` (default: `2`) - step to increase zoom level my each zoom in; `zoomOutButton` - an instance of button which is shown when chart is zoomed in.
- `ForcedDirectedTree`: new zoom-related methods: `zoomToPoint(point, level, center)` and `zoomToDataItem(dataItem, level, center)`;
- New global function: `am4core.createDeferred(callback, scope, ...parameters)`. Can be used to create multiple charts in a truly safe daisy-chain (next chart starts to be instantiated only when previous triggers a `ready` event). Returns a `Promise` with chart instance. [More information](https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation);
- New global option: `am4core.options.deferredDelay` (default `100`). Specifies time-gap in milliseconds between deferred chart instantiations.

### Changed
- Added date ordinal translations for Chinese locales.

### Fixed
- Accessibility: `readerTitle` was not being properly populated with data on `Label`.
- Accessibility: `readerDescription` was not being populated with data.
- Now works with Angular Universal SSR. Please refer to our [Angular doc](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) for instructions on how to structure your app for SSR to work properly.
- When `MapChart` was panned with inertia and a polygon with `zoomToObject()` hit event was clicked when the map was still moving, the map was zooming into a wrong position.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by shaunvdp** [comment]
Hi there. I see this particular issue has been sorted and the bouncing looks great. However, this issue persists when velocityDecay is set to 1. you can drag node off the canvas, and when you drop them you cannot get them back :( 

is there a work around for this?

Thanks for the great work!
