### ISSUE TITLE
artefacts appear after export

### ISSUE THREAD

**Issue by PepiBobanov** [amcharts/amcharts4#2112]
After exporting i get these artefacts.

![artefacts](https://user-images.githubusercontent.com/37262013/74100007-7f098600-4b32-11ea-9ff7-9e812b368d0d.png)

i use this settings:
dateAxis.tooltip.exportable=false;
valueAxis.tooltip.exportable=false;
series.tooltip.exportable = false;
chart.scrollbarX.exportable = false;
chart.cursor.exportable=false;

When i do export to image, it appears some flicker and then this artefacts appears.
I think the key could be to disable tooltips before exporting, i've tried on 'exportstarted' but it does not work.
I think how to disable tooltips, when export menu shows, and when it hides to enable them, but i don't find such events

**Comment by martynasma** [comment]
Fixed in [4.9.0](https://github.com/amcharts/amcharts4/releases/tag/4.9.0).

## [4.9.0] - 2020-02-09

- New plugin: [Venn Diagram](https://www.amcharts.com/docs/v4/chart-types/venn/).
- `ForceDirectedSeries.dragFixedNodes` property added (default `false`).
- `ForceDirectedSeriesDataItem.percent` getter added.

### Fixed
- Mouse interactions were not working properly in very old (pre-59) FireFox.
- Dynamically changing `ForceDirectedSeriesDataItem.fixed` was not working.
- `CirclePattern` was not being globally exported.
- Setting `expoirtable = false` on some elements that are invisible sometimes caused them to become visible after export.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by PepiBobanov** [comment]
works fine now.  that was fast fix

**Comment by IkamThorek** [comment]
Tooltips are still shown on exports to me. I am using Chrome v80.

https://stackblitz.com/edit/typescript-dy7ew7
