### ISSUE TITLE
AmCharts with Angular 6 doesn't work properly with AxisRanges

### ISSUE THREAD

**Issue by VictorJuliani** [amcharts/amcharts4#217]
Hello!

I've taken the sample Angular app from v4 docs and tried to build a demo chart loading data asynchronously.
In this chart, I added one guide line and one axis range with value/endValue to fill the chart in another color on a specific interval.

This scenario strangely causes the AmChart script to freeze and browser prompts me to interrupt it.
Here is a simple CodePen repro with the issue: https://codepen.io/victorjuliani/pen/zLyNRQ?editors=0010
The repro has no zone for I could not inject NgZone to it, but it has makes no difference (my local app runs with NgZone and it has the same failure).

The combination of guide line **without label** + axis range + async data loading seems to be the root of the problem, though I cannot tell why.

Any of the following changes are valid workarounds to avoid freezing:
1. adding an empty texted label to the guide line (the easiest one);
2. removing the axis range (value/endValue);
3. loading data synchronously.

**Comment by martynasma** [comment]
Looks like the issue is not in Angular setup, but rather in our JSON config parser.

Here's the same chart with exactly your setup, using object based setup, working fine with async data:
https://codepen.io/team/amcharts/pen/101f88e523cd1617efc8a263803b6b17

And here's standalone in JSON config, failing:
https://codepen.io/team/amcharts/pen/6653a05d60a3fe2bd7c0011bdf945644?turn_off_js=true
(note it has JS turned off so that it does not hang the whole tab)

We are going to look into this, and keep you posted.

**Comment by martynasma** [comment]
This is weird. I can't seem to be able to reproduce this in our local dev env.

It might be because we already fixed something that fixed this.

Let's revisit this after we release the new version in the coming days to see if the issue still persists.

**Comment by martynasma** [comment]
We've just released beta.43. The chart does not fail anymore for me, even with async data.

Please let me know if it's fixed on your end as well.

**Comment by VictorJuliani** [comment]
Hi @martynasma !

I have tested version beta.43 locally and the issue appears to be gone. However, on my codepen it still occurs! The amCharts library imported are (should be) the latest. To make another test, I've created a new pen without the Angular part and it's also happening there
https://codepen.io/victorjuliani/pen/VBRXNw?editors=0010

**Comment by martynasma** [comment]
I don't get the issue with the codepen you shared.

Could be that old CDN version of the js files is still cached in your browser? Can you try clearing browser cache and reloading?

**Comment by VictorJuliani** [comment]
I did clear the cache and checked what version was described in core.js loaded by the CodePen (it was beta.43).

![image](https://user-images.githubusercontent.com/7915114/44032345-31f8a3bc-9edd-11e8-9b49-25ee143d6584.png)

Whenever I comment out the "label" section from axisRanges, the chart wont load (the blank part of the image below is where the chart should be rendered):
![image](https://user-images.githubusercontent.com/7915114/44032214-dadbd770-9edc-11e8-94ee-fae70df44a14.png)

This happend to me on Firefox and Chrome (though Chrome doesn't have a message like Firefox does).

**Comment by martynasma** [comment]
Weird, I'm not able to reproduce this. Both with label section active and commented out. The chart just shows up.

Since we both can't reproduce this locally, would you agree on shelving this until you hit it in your local env?

**Comment by VictorJuliani** [comment]
Sure! I just mentioned about the CodePen in case you were able to reproduce the issue in first place, but if that's not the case, then no problem leaving on background in case it happens again.

**Comment by martynasma** [comment]
Perfect. I'm gonna go ahead and close this. But feel free to reopen or comment, should the issue resurface.

**Comment by VictorJuliani** [comment]
Hi @martynasma!

I've run into this issue again, but it happens to me now when there are 2 or more series on the chart and I pass the mouse over it (to see tooltips). I'm not sure which version caused this, but its 43 or higher and probably due to the the recent fix of DateAxis nearest point to display the tooltip

I managed to get the stack call causing the trouble now:
```
./charts/axes/DateAxis.js/DateAxis.prototype.getSeriesDataItem@
./charts/series/XYSeries.js/XYSeries.prototype.showTooltipAtPosition@
./charts/types/XYChart.js/XYChart.prototype.showSeriesTooltip/<@
each@
./core/utils/List.js/List.prototype.each@
./charts/types/XYChart.js/XYChart.prototype.showSeriesTooltip@
./charts/types/XYChart.js/XYChart.prototype.handleCursorPositionChange@
./core/utils/EventDispatcher.js/EventDispatcher.prototype.on/<@
./core/utils/EventDispatcher.js/EventDispatcher.prototype.dispatch/</<@
triggerIdle@
./core/System.js/System.prototype.update@
./core/System.js/System.prototype.update/<@
```

To be more precise, the exact point where it hangs is the _while (date.getTime() < this.maxZoomed) {_ loop of DateAxis#getSeriesDataItem;

However, by looking at the at the output from my CodePen above, I believe these issues have different sources, for the CodePen generates a completely different stack trace every time it runs.

If you can't reproduce it, I'll try to build a simple repro later.

**Comment by martynasma** [comment]
@VictorJuliani Can you produce a CodePen for your chart that displays this issue?

I tried replicating it, but don't get the error on standalone (non-Angular) setup:

https://codepen.io/team/amcharts/pen/82ced1a6f244fbe7fda8251c16fdbf33

**Comment by dyzajash** [comment]
Bump. Bug occurred on 4.4.X branch again. 

Link provided in https://github.com/amcharts/amcharts4/issues/217#issuecomment-416022096 is replicating issue.
