### ISSUE TITLE
syncWithAxis sometimes... does not sync axes

### ISSUE THREAD

**Issue by floklein** [amcharts/amcharts4#2235]
Hi!

When creating a series along its axis, sometimes `syncWithAxis` does not sync axes on first render.
It also happens when zooming, dezooming, editing data, etc, especially without the animated theme.

Here is a CodePen: https://codepen.io/floklein/pen/VwLQraL

Steps to reproduce:
- Add multiple series/axes in a row
- Zoom once to make axes sync working

**Comment by martynasma** [comment]
Yes, it's an experimental feature, which might not work.

That said, I suspect we might not be handling the addition of new series/axis as an event to trigger syncing, so that might be solvable.

We'll keep you posted.

**Comment by floklein** [comment]
Thanks for answering! Looking forward to your response.

**Comment by zeroin** [comment]
So the problem is this - you can not use adapter for syncWithAxis, as only a setter adds listeners required for this to work. So instead of adapter, you simply need to set it using setter:

https://codepen.io/team/amcharts/pen/f7930d26501f3557849c41c113117f0f

**Comment by floklein** [comment]
Problem is if the first axis is deleted, the other axes need to update their `syncWithAxis` property to the new 0-index axis.

Also, `syncWithAxis` is listed as a valid adapter for `ValueAxis` : https://www.amcharts.com/docs/v4/reference/valueaxis/#syncWithAxis_adapter

**Comment by zeroin** [comment]
Then it's our mistake in the docs, sorry.
It means that when axis is removed, you should set new syncWithAxis, unfortunately I don't see other option.

**Comment by zeroin** [comment]
BTW, when playing with your demo I found some issues with removing series, not sure if you stumbled on them. They will be fixed in next release.

**Comment by floklein** [comment]
> It means that when axis is removed, you should set new syncWithAxis, unfortunately I don't see other option.
Ok I will do that.

> BTW, when playing with your demo I found some issues with removing series, not sure if you stumbled on them. They will be fixed in next release.
What are those issues? Are you talking about my demo on [this other issue](https://github.com/amcharts/amcharts4/issues/2234)?

**Comment by floklein** [comment]
> Then it's our mistake in the docs, sorry.
> It means that when axis is removed, you should set new syncWithAxis, unfortunately I don't see other option.

So I tried that, and I don't think it works: https://codepen.io/floklein/pen/LYVdLKG

**Comment by floklein** [comment]
> So I tried that, and I don't think it works: https://codepen.io/floklein/pen/LYVdLKG

It works if you call `chart.invalidateData()` after, or edit chart data: https://codepen.io/floklein/pen/wvamqKj

**Comment by zeroin** [comment]
Strange, the demo: https://codepen.io/floklein/pen/LYVdLKG always syncs axes for me. 
Let's try this again after the update we are releasing tomorrow.
As for the issues - if you add a series in your demo and then remove it, the chart will display a single date vertical line.

**Comment by martynasma** [comment]
Fixed in [4.9.7](https://github.com/amcharts/amcharts4/releases/tag/4.9.7).

## [4.9.7] - 2020-03-14

### Added
- Export has now additional setting `dataFieldsOrder`. It's an array. Push field names into it and exported data will try to maintain field order like this.
- A read-only property `tooltipDate` added to `DateAxis`. Will holde `Date` object of the last shown axis tooltip.

### Fixed
- In charts with series loading their own external data with responsive features enabled, they were starting as pre-hidden.
- Axes in `XYChartScrollbar` (both value and date) were not reseting min/max if series of the chart changed. This could result scrollbar's series incorrectly displayed.
- `PyramidSeries` and `FunnelSeries` with very small values were not animating properly on chart init.
- `PyramidSeries` and `FunnelSeries` with data items with `value = 0` could show small rectangle at top/left corner.
- `PyramidSeries` with data items with `value = 0` was not rendered properly.
- Tooltip on a horizontal axis was "shaking" when cursor was very near plot area.
- Performance improved of adding series to an already build `XYChart`.
- Map was not drawn with certain initial `deltaLongitude` values (e.g. 30, 60, etc).
- Removing series with a lot of data, `DateAxis` with grouping enabled, and zoomed-in chart could cause a stack overflow.
- Removing series could cause error (if removed while initial animation was still playing out).
- Sometimes, if a series was added after chart was inited and data grouping of `DateAxis` was enabled, the `ValueAxis` was not fully zoomed out.
- A newly added series after the chart was inited was not showing initial animation.
- Violating logarithmic axis scale no longer results in critical / chart-stopping error. The modal can be closed and chart recovered.
- If chart had stacked axes and series with bullets, the bullets were not masked properly. Now you can set `series.maskBullets = true` to solve this.
- Series tooltip is no longer shown if data item is outside plot area.
- Perfectly straight line series in `XYChartScrollbar` were not displayed.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by floklein** [comment]
Still an issue...
![chart](https://user-images.githubusercontent.com/4128942/76889720-68b7be00-6886-11ea-8f36-aefbeb78090c.png)

**Comment by zeroin** [comment]
Does this happen a lot?
I am aware that this will not work in 100% cases, especially with many axes. We have a note that this feature is experimental and not bullet proof. I could try to take a look anyway, but I'd need a reproducible demo of the exact situation.

**Comment by floklein** [comment]
Happens almost everytime with around 5 axes and more.
I tried to fake a bit of lag with console logs here: https://codepen.io/floklein/pen/wvaXjOj

**Comment by rpg-verodin** [comment]
@zeroin I have this happening regularly with only 2 axes (left and right)
