### ISSUE TITLE
Amcharts4 legend label not truncated when value is right aligned

### ISSUE THREAD

**Issue by pragatheeswaranshf** [amcharts/amcharts4#2338]
I am creating a pie chart with the legend at the bottom. I have added the config to truncate the legend label by passing

```
chart.legend.labels.template.maxWidth = 120;
chart.legend.labels.template.truncate = true;
```

Works fine until i try to right align the value by passing

```
chart.legend.valueLabels.template.align = "right";
```

After adding this, the labels are not truncated and occupy the full width. 
<img width="1006" alt="charts-demo" src="https://user-images.githubusercontent.com/46960095/79070089-f0131880-7cf0-11ea-9898-26faa3b38d9c.png">

Any help on how to achieve both truncating and also having the values aligned to the right would be much appreciated. 

Also I could not find any adapter method to overwrite the label before being rendered like `tooltipHTML`. If so, I can strip the label after certain characters and return.

Here is a [Codepen demo](https://codepen.io/Pragatheeswaran/pen/QWjwNer) of the above mentioned issue. I have asked this in [Stack Overflow](https://stackoverflow.com/questions/61143986/amcharts4-legend-label-not-truncated-when-value-is-right-aligned) also but didn't get a response yet.

**Comment by martynasma** [comment]
It seems a bug due to fuzzy logic associated with aligning of stuff in columns. In reality right-aligning value labels works only OK for legends with a single column.

We'll see if we can fix this. Though, at this point I can't provide an ETA for a fix.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.9.18](https://github.com/amcharts/amcharts4/releases/tag/4.9.18).

## [4.9.18] - 2020-04-28

### Added
- Heatmaps can now be logarithmic (set `logarithmic = true` in the heat rule config).

### Fixed
- Preloader label was misaligned when RTL was enabled.
- Double "hit" event invocation on `MapPolygon` fixed.
- Regression plugin: "processed" event was triggered twice on initial chart load.
- SliceGrouper plugin: if slice templats had any "hit" events set, `clickBehavior = "break"` was not working.
- IE was not displaying series in `XYChartScrollbar`. On IE now gray fill/stroke is used instead of desaturate filter.
- IE was not displaying series with filters. Remnoved filters if IE.
- Fixed issue with zero-value nodes drill-down `SankeyDiagram`.
- When animations were disabled through options, showing `XYSeries` and `FunnelSeries` after it was hidden was not working.
- It was not possible to add `MapImages` to `MapImageSeries` directly from the GeoJSON geodata.
- `maxWidth` set on Legend's label was being ignored.
- Layout was not being redrawn when `minGridDistance` was set after chart initialization.
- If `sprite.showTooltipOn = "hit"` and no animated theme was used, tooltip used to flicker at old position before shown in the correct one.
- EDGE was not showing `ColumnSeries` gradients if gradient was set on series, not on directly on column template.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Chaitanya-abacusai** [comment]
I'm using "@amcharts/amcharts4": "4.10.28", and still seeing issue with truncation and maxWidth when position is "bottom"
