### ISSUE TITLE
Memory leaks && Performance issues with multiple line charts

### ISSUE THREAD

**Issue by DomDomHaas** [amcharts/amcharts4#2395]
**Bug description**

I'm creating multiple charts which are shown different sensor data from measuring stations in greenland. So I have a page with multiple charts on it and when switch to another station the charts are disposed (via vue.js beforeDestroy method) and recreated with the data from the other station.

However when monitoring the memory which is used by chrome, I can see that only a fraction of the memory gets released. I've added logs to see which of the charts gets disposed, they all get disposed but the memory isn't released.

Reproduciton:

- Go to https://www.wsl.ch/gcnet/testing/memory/
- click on first station "Swiss Camp 10m" in the station list menu
- scroll down to load all the charts
- check the memory use of chrome via Task manager
- open dev tools to check the logs and the disposed chart names (should be 16)
- click on the second "Swiss Camp" station in the station list menu (which takes a long time)
- check the memory again

I've implemented a Intersection Observer to not load all the data and charts at once when entering the page because that is not performant. So make sure to scroll down and wait for the all the charts to load.

For this use case the sources are here:
Page component:
https://github.com/EnviDat/gcnet-frontend/blob/feature/memory_testing/src/components/Pages/StationsDetailPage.vue
Charts component:
https://github.com/EnviDat/gcnet-frontend/blob/feature/memory_testing/src/components/DetailChart.vue
js function for the XYChart, the function createLineChart() is called:
https://github.com/EnviDat/gcnet-frontend/blob/feature/memory_testing/src/chartData/charts.js

Related frameworks:
- vue.js version 2.6.11
- amcharts4 version 4.9.10
  (just updated to 4.9.17 and tried again, ~~doesn't do anything~~ **it does seem to do the trick** the change log didn't suggest anything though...)

Also the performance in general is much worse then amCharts v3, compare here:
https://www.wsl.ch/gcnet/

**Comment by zeroin** [comment]
Hi,

Thank you for the insights. So the first question is - you say that the new version does the trick, do you mean that there is no memory leak with this version?

If it still is, I am afraid we can only investigate this if you could provide us with an isolated from any framework case of a chart or charts which, when disposing produces memory leak.

**Comment by DomDomHaas** [comment]
I do further testing. It looks like chrome does release the memory after a while with the latest version (4.9.17). 

But the performance isn't good at all... Is there no vue.js knowleged on your team to investiage?

Btw. the docs about vue.js should have a mentioning about the beforeDestroy() method from vue.js which calls the dispose() of a chart. Similar to react.js.

**Comment by SharpBCD** [comment]
@DomDomHaas, can you do me a favor? Please check how your charts perform on Chrome vs FF and (sounds crazy, I know) when devTools is open vs closed.
I noticed huge differences for some simple math ops: 
- without the chart: 1-2 ms, all 3 browsers.
- with chart (simple barChart with 12 items, the months): FF 8-25ms, Chrome: 170-220ms.
For Chrome, with devTools closed, I get lower values. 

How weird is that? 

I suspect there is a `nextTick` somewhere that is called far too many times. I did not had this problem on a previous version of amchart4 but I don't know the version. It is live although.

**Comment by simvol** [comment]
@SharpBCD its funny, I just spent ~4 hours analyzing performance - and your suggestion does work. With devtools closed it is significantly faster. However, one AmCharts drastically changes loading time for my whole dashboard page. (there are 2 more c3js charts on the page, which I was going to replace with AmCharts, until I noticed huge performance problem..)

We are also using Vue. One issue I solved is setting chart on "this" (component). It makes Vue wrap every single property on the chart with getters/setters. So "this.chart" is a bad idea, but unfortunately fixing this didn't solve all the problems. 

This is how my record looks like: 1+ second for "Animation Frame Fired", followed by 1+ second of animations that are actually lagging :(

![image](https://user-images.githubusercontent.com/10889961/80561997-28765000-899b-11ea-9875-6a9d3125e4a9.png)

**Comment by SharpBCD** [comment]
@simvol  oh good.... that makes me feel like I'm not the only crazy man in the Vue-Amchart universe.

Here's what I also learned and it is also freaking weird:
I have a simple list with the customers (see picture). It selects the customer and you can see simple chart with monthly sales performance.
Here is the weird stuff:
1. If the customer list contains 2-3 elements, the rendering is relatively fast.
2. If the list has 20 items:
 - it is visible with the naked eye how slow it is when it renders
 - any other math is taking a huge amount of time to compute. + bonus on Chrome with devtools on
- I can hear the cooler on my processor accelerating as the cores are getting to 100%

(there is no bug or memory leak, the code for the list is too simple)

My suspicions: 
 - ver 1: Somewhere in amcharts code there is a nextTick() that is called far too often. The whole chart is re-redered on each nextTick
 - ver 2: There is a memory leak, recursion or similar, again associated with reactivity.
In both cases, I have a older version (4+), running on server where this problem does NOT exist but on that version I had to call nextTick() when updating data, otherwise the chart was "dirty".
And yes, I also moved the chart var from reactivity but there was no impact on performance
![amchart bug](https://user-images.githubusercontent.com/31144210/80582439-631dce00-8a17-11ea-838a-e1fad1a98421.png)

**Comment by martynasma** [comment]
@DomDomHaas @SharpBCD @simvol 

People, we just released 4.9.19. It removes a third party resize sensor we were using, which was causing issues in some case, especially Chrome 81 with DevTools open. Crazy, I know. Disposing and some other stuff should be faster.

I'm eager to know if this has any positive impact on your Vue setups.

**Comment by SharpBCD** [comment]
![image](https://user-images.githubusercontent.com/31144210/80797259-07d01500-8baa-11ea-9d46-5f434e7a991f.png)
Muuuchhh better!

**Comment by simvol** [comment]
@SharpBCD could you share how you measure this time? I still have some lagging.. curious if I'm doing something wrong.

**Comment by SharpBCD** [comment]
it simple decrease of Date.now() at the beginning and end of the update function. Any math was taking a huge amount of time. It is still not perfect, with the chart disabled this time goes to 1-2ms and the math here have nothing to do with the chart. I compute some values in a local var and only then I pass them to the chart.data.
Not perfect but I can live with it.

**Comment by simvol** [comment]
@martynasma is there any metrics you would suggest to check the performance? I can only visually tell it is slow/labels are flickering/stacked bars appear with delay one at a time. But I'm not sure what would be good metric to check.
