### ISSUE TITLE
Order of events?

### ISSUE THREAD

**Issue by sassomedia** [amcharts/amcharts4#2426]
What I'm struggling with is getting events to work in the right order. It almost seems like events are firing in the capturing phase as opposed to the bubbling phase. 

As an example use case: a regular column chart where on click on one of the columns, the rest of the columns are set to a dimmed state. Clicking on any of the dimmed columns sets its state back to default and setting the previous column to a dimmed state. Basically, highlighting the clicked column. That all works fine and is simple enough to do by attaching a `hit` event onto the columns template. In order to reset everything to default when I click anywhere but the columns, I add a `hit` event to the chart. 

And that's where I run into an issue. The chart event always fires first, even if I click on a column. I would expect the column event(target) to fire first so that I could stop the propagation from bubbling up to the chart. But since the chart event always fires first, it always resets before anything else gets handled. That can cause flicker and other unintended behavior.

Looking back at some older v3 charts, the event bubbling did work as expected. Is there anything different in v4 that I'm missing?

**Comment by martynasma** [comment]
We'll need to to figure out if this is fixable.

Working pen for reference:
https://codepen.io/team/amcharts/pen/18d65530c6cf366ae6d2e285cb878bf1?editors=0010

**Comment by sassomedia** [comment]
Correct, that is a much simpler example. Thanks!

**Comment by martynasma** [comment]
Fixed in [4.9.20](https://github.com/amcharts/amcharts4/releases/tag/4.9.20).

## [4.9.20] - 2020-05-11

### Changed
- `hit` and `up` events on nested objects will now respect correct bubbling up order.
- If `rtl` is not set directly on the `Label`, it will now take `rtl` value not from its parent but from `baseSprite` (performance enhancement).
- `<desc>` element with amCharts attribution removed from generated SVG.

### Fixed
- Export: PDF export will now fallback to regular fonts if bold fonts don't exist.
- Export: Advanced PDF exports with extra content were broken since last release.
- Export: Image export was essentially broken in IEs.
- `options.nonce` was not working properly on EDGE.
- Event `selectedned` was not dispatched by `Cursor` if released outside the chart div and behavior was set to `select*`.
- If all series were removed and then added quickly to the chart with a legend it could result a JS error.
- Setting `data` directly on a series not right after it was created could result `series.data` array to be shown as empty.
- It was impossible to set `SwitchButton` as active initially.
- Fixed snapping cursor to series when data was missing: if series had gaps in data and `cursor.snapToSeries` was set, the snapping was not working properly.
- When adding data to `XYSeries` which was `XYCharScrollbar`'s series, the raw data was incorrectly modified.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by sassomedia** [comment]
@martynasma Great, thanks! This works now, at least in the sense that the inner even is firing first. I'm still not able to stop the bubbling but I can now handle the second event with a variable.
