### ISSUE TITLE
XYChartScrollbar does not display when using options for queue and showOnViewport

### ISSUE THREAD

**Issue by matthewjhoward** [amcharts/amcharts4#2714]
**Bug description**

XYChartScrollbars do not render when the following options are enabled.
```
am4core.options.onlyShowOnViewport=true;
am4core.options.queue=true;
```

I have reproduced the issue at this [CodePen](https://codepen.io/matthewjhoward/pen/PoZxOXO) by modifying the [Date Based Data Demo](https://www.amcharts.com/demos/date-based-data/) to toggle these options on and push the chart down out of the viewport.

**Environment (if applicable)**

- amcharts 4.9.30
- Tested on Google Chrome 84.0.4147.89, Safari 13.1.1 (15609.2.9.1.2), Firefox 77.0.1

**Additional context**

I believe this issue is caused specifically by the option `am4core.options.queue=true;`. I am unable to reproduce the bug outside of my development environment with just this option, but I encounter this bug when I have this option turned on regardless of my `onlyShowOnViewport` setting.

**Comment by martynasma** [comment]
Fixed in [4.9.31](https://github.com/amcharts/amcharts4/releases/tag/4.9.31).

## [4.9.31] - 2020-07-21

### Changed
- Global adapters are being deprecated due to performance reasons. They will still work on some properties, but may be turned off at some future version. If you are using `am4core.globalAdapter`, please consider refactoring your code in some other way.
- If `groupInterval` is manually set, `DateAxis` now prepares all intervals. Normally, the chart does not prepare data sets for time intervals longer than the span of dates in the data. This causes problem in case user sets these intervals manually using `groupInterval`. Note, the groupInterval must be set initially, before data parsing in order data to be grouped into all groupIntervals.

### Fixed
- "Year of week" (`YYYY`) was not being calculated correctly by `DateFormatter`.
- Regression plugin was not working correctly in an all-`ValueAxis` scenarios.
- `ColumnSeries` were not working with `dropFromPreviousState`.
- If data was changed on a chart which was zoomed and there were less data items in the new data than there was before, a JS error was triggered.
- Sometimes a chart with `XYChartScrollbar` with series in it could produce a JS error if series has its `fillOpacity > 0`.
- Series in an `XYChartScrollbar` was not being shown if `options.onlyShowOnViewport = true`.
- `zoomToRectangle()` call was resulting in an error if called after the `MapChart` was rotated.
- `CurvedColumnSeries` columns were not being filled with proper color (black was being used instead).
- A chart with multiple series starting/ending not at the same position could result in wrong zoom on `ValueAxis`.
- `DateAxis` with millisecond `baseInterval` sometimes could show one millisecond less than actual data point in its tooltip.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by matthewjhoward** [comment]
This issue still exists with option `options.queue = true`. It appears that if the chart containing the XYChartScrollbar is not first in the queue, then the XYChartScrollbar series does not display properly.

I have reproduced the issue again at this [Code Pen](https://codepen.io/matthewjhoward/pen/zYreOWd).

This issue is independent of setting `options.onlyShowOnViewport`.

**Comment by martynasma** [comment]
Fixed in [4.9.33](https://github.com/amcharts/amcharts4/releases/tag/4.9.33).

## [4.9.33] - 2020-07-23

### Fixed
- If an item from a chart with `CategoryAxis` was removed and then a new item with the same category name was added, chart was not rendering the new item.
- A chart with multiple series starting/ending not at the same position could result in wrong zoom on `ValueAxis`
- Last bullet/column from `XYSeries` could disappear if end date was not exact as last data items date.
- `LineSeries` could skip a point in case distance between data points was very small, resulting in incorrect line series.


[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
