### ISSUE TITLE
When zooming on a MapChart while panning the wrong point is centered

### ISSUE THREAD

**Issue by JonasGilg** [amcharts/amcharts4#2806]
**Bug description**
The `zoomToMapObject` function centers the wrong point on a MapChart while panning.

Here is a minimal working example: https://jsfiddle.net/et80bqmu/

Steps to reproduce:
1. Zoom in a little bit using the mouse wheel.
2. Start panning with the mouse.
3. While the pan animation hasn't finished click on a state to zoom on.
4. The zoom should now center on the wrong point.

**Environment**
- amCharts version: 4.9.31
- Browser: Chrome  84.0.4147.135

**Comment by martynasma** [comment]
Fixed in [4.10.0](https://github.com/amcharts/amcharts4/releases/tag/4.10.0).

## [4.10.0] - 2020-09-01

### Added
- New `LineSeries` property: `smoothing` (`"bezier"` (default), `"monotoneX"`, and `"monotoneY"`) - indicates algorithm to use for smoothing the lines. Monotone algos are better suited for irregularly-spaced data. [More info](https://www.amcharts.com/docs/v4/chart-types/xy-chart/#Alternate_smoothing_algorithm).
- `ForcedDirectedTree`: new property `zoomable` (default: `false`). If set to `true`, the chart will be zoomable/draggable using mouse, touch, or API. [More information](https://www.amcharts.com/docs/v4/chart-types/force-directed/#Zooming).
- `ForcedDirectedTree`: zoom related properties added. `mouseWheelBehavior` (`"zoom"`, `"none"`) - controls what happens when mouse wheel is used over chart; `zoomStep` (default: `2`) - step to increase zoom level my each zoom in; `zoomOutButton` - an instance of button which is shown when chart is zoomed in.
- `ForcedDirectedTree`: new zoom-related methods: `zoomToPoint(point, level, center)` and `zoomToDataItem(dataItem, level, center)`;
- New global function: `am4core.createDeferred(callback, scope, ...parameters)`. Can be used to create multiple charts in a truly safe daisy-chain (next chart starts to be instantiated only when previous triggers a `ready` event). Returns a `Promise` with chart instance. [More information](https://www.amcharts.com/docs/v4/concepts/performance/#Deferred_daisy_chained_instantiation);
- New global option: `am4core.options.deferredDelay` (default `100`). Specifies time-gap in milliseconds between deferred chart instantiations.

### Changed
- Added date ordinal translations for Chinese locales.

### Fixed
- Accessibility: `readerTitle` was not being properly populated with data on `Label`.
- Accessibility: `readerDescription` was not being populated with data.
- Now works with Angular Universal SSR. Please refer to our [Angular doc](https://www.amcharts.com/docs/v4/getting-started/integrations/using-angular2/) for instructions on how to structure your app for SSR to work properly.
- When `MapChart` was panned with inertia and a polygon with `zoomToObject()` hit event was clicked when the map was still moving, the map was zooming into a wrong position.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by JonasGilg** [comment]
The issue is not fixed. I tested it with Chrome, Edge and Firefox. I cleared the cache of all three browsers.

**Comment by martynasma** [comment]
This might still be happening, but should be much much less prominent then before update. It shouldn't be a very noticeable issue with normal use (not trying to reproduce on purpose). We might come back to this in the future, but not sure if/when, since it does not seem like a very glaring issue anymore.

**Comment by JonasGilg** [comment]
Ok, thank you for the info. Can you reopen the issue, so I get a notification in case you fix it completely?

**Comment by martynasma** [comment]
If we make any updates in that regard, we'll post a follow up comment, in which case you will get a notification, too. Hope that's OK.

**Comment by JonasGilg** [comment]
I'm fine with that. Thank you for your trouble.
