### ISSUE TITLE
After zooming by date and hidding a series, then zooming back out and showing series the series doesn't show

### ISSUE THREAD

**Issue by JackShepard98** [amcharts/amcharts4#2860]
Hi,

I am using an XYChart with DateAxis on the x axis, and one ValueAxis on the y axis. I have multiple series and I have groupData set to true. I noticed the following behavior (seems to happen only when groupData is true or there is data to group)
1. Zoom on a time period using the cursor
2. From the legend hide the highest  on the y axis(or lowest) series
3.Zoom out to initial time period
4. From the legend click to show the hidden series
Expected behavior: Series shows again
Actual behavior: The series doesnt show, it seems that the value axis remains at a lower scale and doesnt go back to the higher values. But if I zoom in again the series shows.
I have a gif that shows the behavior: 
![notworking](https://user-images.githubusercontent.com/36894163/92211482-36803400-ee99-11ea-88bf-ed1b0d698629.gif)

Also below is a example with a series in the middle where I do the exactly same thing but it works:
![working](https://user-images.githubusercontent.com/36894163/92211690-82cb7400-ee99-11ea-886c-6fce6cf5ba49.gif)

Anybody knows how to fix this?
Thanks

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by JackShepard98** [comment]
> Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

I could not post the original code because there are back end calls involved but I modified a codepen from the official documentation: [https://codepen.io/jackshepard98/pen/JjXOZmd](https://codepen.io/jackshepard98/pen/JjXOZmd) .In this example the series named value1 (with color red) doesn't show.

**Comment by martynasma** [comment]
Thanks! We're looking into it and will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.10.1](https://github.com/amcharts/amcharts4/releases/tag/4.10.1).

## [4.10.1] - 2020-09-07

### Added
- New `DateAxis` property: `timezone`. Allows setting timezone to recalculate data in, e.g. `"Australia/Sydney"`. Make sure not to set this on both axis and date formatter.
- New `DateFormatter` property: `timezone`. Allows setting timezone to recalculate date objects to before applying the format, e.g. `"Australia/Sydney"`.
- New global option: `am4core.options.disableHoverOnTransform` (`"never"` (default), `"touch"`, `always`)). Allows disabling all hover activity when some element is being dragged or resized. [More info](https://www.amcharts.com/docs/v4/concepts/touch/#Hover_functionality).

### Changed
- Now `SankeyLink` that points "backwards" will be applied `"backwards"` state (if created) so you can style it differently than regular links.

### Fixed
- Accessibility: data placeholder population was not working on bullets if Animated theme was not enabled.
- Tapping on a chart with `Cursor` was triggering an on-screen keyboard on some mobiles devices.
- Some TypeScript warnings were fixed.
- A chart with `DateAxis` and `groupData = true` could result a JS error if a series had bullets and a lots of data points.
- In a chart with `DateAxis` and `groupData = true`, if a series was hidden when zoomed-in, then zoomed-out, and then unhidden, the related  `ValueAxis` was not updating it's min/max to available value range.
- In some cases a heat rule could result in infinity value which would lead to drawing errors.
- Errors when cloning a `RadarChart` from a template fixed.
- `SankeyDiagram` used to produce stack owerflow error if data contained backward links. Now it will correctly draw a link.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by JackShepard98** [comment]
HI,
I tested the fix in the new release and it works only if animated theme is set. If not the bug still persists.

Thanks

**Comment by martynasma** [comment]
Sorry about that. We'll fix it (again) in the next version, and will let you know here.

**Comment by martynasma** [comment]
Fixed in [4.10.3](https://github.com/amcharts/amcharts4/releases/tag/4.10.3).

## [4.10.3] - 2020-09-19

### Added
- RangeSelector plugin: a new event `periodselected` added to `DateAxisRangeSelector`.
- `DateFormatter` now supports quarter format (code: `"q"`).

### Changed
- More prompt translations to Indonesian locale (`id_ID`).

### Fixed
- JSON config: Some axis' `title` property was being overwritten if it wasn't last option in the properties list.
- SliceGrouper plugin was sometimes not functioning properly when used with `options.queue = true`.
- Scrollable legend was not resetting back to top if its height changed.
- `TreeMap` with `binaryTree` algorithm was producing a JS error if no initial data was set on chart.
- If data grouping on `DateAxis` was enabled and there were more than one series in the chart, the second and other series were rendered with data ungrouped in the background before rendering them correctly and thiswas causing performance issues.
- Vertical `CurvedColumnSeries` with non-inversed `CategoryAxi`s were not positioned properly.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
