### ISSUE TITLE
Amcharts4 - NuxtJS - Internet explorer

### ISSUE THREAD

**Issue by Toni-hr98** [amcharts/amcharts4#2907]
Greetings, 
I am having problems with amcharts4 in a nuxtJS project on IE. The error I get is: SCRIPT1002: syntax error. 
![Schermafbeelding 2020-09-15 om 10 45 17](https://user-images.githubusercontent.com/56109782/93211701-e3906180-f761-11ea-977a-9add1e3271ed.png)

I tried to transpile amcharts like this:
transpile: [
            ({isLegacy}) => isLegacy && '@amcharts',
]

But that did not work. I also tried to put: import "core-js"; at the top of the nuxt.config.js file. But that also didnt do the job.

Can someone help me?

**My files:**

**nuxt.config.js**
plugins: [
        {src: '~plugins/amcharts.js', mode: 'client'},
]

**amcharts.js:**
import * as am4core from "@amcharts/amcharts4/core";
import * as am4maps from "@amcharts/amcharts4/maps";
import am4geodata_continents from "@amcharts/amcharts4-geodata/continentsLow";
import am4geodata_middleEast from "@amcharts/amcharts4-geodata/region/world/worldRegionsLow";

import Vue from "vue";

Vue.prototype.$am4core = () => {
	return {
		am4core,
		am4maps,
		am4geodata_continents,
		am4geodata_middleEast
	}
}

**package.json**
"dependencies": {
    "@amcharts/amcharts4": "^4.10.2",
    "@amcharts/amcharts4-geodata": "^4.1.17",
}

**Comment by martynasma** [comment]
Heads up, we're looking into it. Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.10.5](https://github.com/amcharts/amcharts4/releases/tag/4.10.5).

## [4.10.5] - 2020-10-02

### Changed
- Inline curly-bracket data placeholders now support dot-separated data context names as literal strings, e.g. `"my.custom.property"`.
- A bunch of dependencies were updated to latest versions.

### Fixed
- Toggling `rtl` value on an existing `Label` was (still) not working properly.
- `showSystemTooltip` was being ignored since last version (4.10.4).
- `chart.cursor.snapToSeries` was not causing cursor to snap in wrong place if `groupData` was enabled.
- Bullet tooltip was being hidden even if it had to stay when cursor moved out of the plot area.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Toni-hr98** [comment]
Hey @martynasma ,

I updated "@amcharts/amcharts4" to -> "4.10.5"

But I am still experiencing the issue. 
What do I have to do to make it work?

**Comment by Pauan** [comment]
@Toni-hr98 I tried the following:

1. I created a fresh Nuxt app (using `npx create-nuxt-app`).

2. I created a new `components/Chart.vue` file (by copying the code from our [Vue tutorial](https://www.amcharts.com/docs/v4/getting-started/integrations/using-vue-js/)).

3. I added this to `pages/index.vue`:

```
<client-only>
  <LazyChart />
</client-only>
```

4. The chart displays perfectly in IE.

What is your version of Nuxt?

**Comment by Toni-hr98** [comment]
Okay, so i made a fresh Nuxt app just like you did. I copy pasted the Vue tutorial, and everyting else. And the charts work. But i need the maps. And importing the maps makes it crash.

So by only adding this line of code:

```import * as am4maps from "@amcharts/amcharts4/maps";```

The whole component stops working.


And i also get a log error when loading the component lazy just like you did:

```
[Vue warn]: Failed to resolve async component: function () { return __webpack_require__.e(/*! import() | components/Chart */ "components/Chart").then(__webpack_require__.bind(null, /*! ./components/Chart.vue */ "./components/Chart.vue")).then(function(m) { return m['default'] || m }) }
Reason: SyntaxError: Unexpected token 'export'
```

**Comment by Pauan** [comment]
@Toni-hr98 Oh, sorry, I didn't realize that the problem is only with maps.

You can fix that by adding a [`transpile` property](https://nuxtjs.org/api/configuration-build/#transpile) to your `nuxt.config.js`:

```js
  build: {
    transpile: [/^@amcharts\//, "d3-geo", "d3-array", "tinyqueue"]
  }
```

That is all that is needed to make it work.

**Comment by Toni-hr98** [comment]
Yes!!! This is the solution. Thanks @Pauan 👍

**Comment by refaldy111** [comment]
&¡I 来て
