### ISSUE TITLE
How to disable pan once max zoom is reached?

### ISSUE THREAD

**Issue by datafoo** [amcharts/amcharts4#3272]
Using the cursor to zoom in an `XYChart` that is already zoomed-in to the maximum, will start panning the chart.

Try it there for example: https://codepen.io/team/amcharts/pen/LYVQZob

If you add `chart.mouseWheelBehavior = "zoomX";` at the end of the `js` code section, you will experience the same issue by zooming in with your mouse wheel: the chart starts panning.

So, once the chart has reached its maximum zoom, can we disable the panning?

**Comment by martynasma** [comment]
Fixed in [4.10.16](https://github.com/amcharts/amcharts4/releases/tag/4.10.16).

## [4.10.16] - 2021-03-03

### Fixed
- In some rare cases an critical error could happen on hoverable objects on touch-only displays.
- Zooming and drag-rotating a resized `MapChart` could throw off the map position.
- It was possible to continue zooming the chart using mouse wheel even when max zoom was reached.
- Zooming "inverted" horizontal axis was incorrect.
- Updating data on `SankeyDiagram` in some cases could result in an SO.
- `TreeMap` was showing incorrectly sized nodes with empty children array.
- Sometimes wrapping long strings were causing punctuation at the end of the word to wrap into the next line.
- Dynamically switching `logarithmic` setting for a `ValueAxis` was not updating its scale properly in some cases.
- `SliceGrouper` plugin was not updating properly when manipulating data and/or series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by datafoo** [comment]
I am afraid the problem is not entirely fixed.

Load https://codepen.io/team/amcharts/pen/LYVQZob and you will notice that click-drag-and-drop keeps panning the chart after the max zoom is reached. Note that the panning occurs only in the right direction, never to the left. Moreover, the more to the right the click-drag-and-drop is performed, the more it pans the chart to the right.

Try adding the following lines to https://codepen.io/team/amcharts/pen/yjYWXd and you will notice that the wheel keeps panning the chart after the max zoom is reached.
```js
dateAxis.minZoomCount = 10;
chart.mouseWheelBehavior = "zoomX";
```

**Comment by martynasma** [comment]
Back to it. Thanks.

**Comment by martynasma** [comment]
We're gonna fix the `minZoomCount` + `mouseWheelBehavior` issue in the next version. I'll notify you when it's out (most probably within couple of weeks).

The other issue with pan and zoom would be hard to fix without implementing a huge overhaul on under-the-hood functionality. I'm afraid we won't be able to provide a fix for that.

**Comment by datafoo** [comment]
Thank for letting me know!

**Comment by martynasma** [comment]
Fixed in [4.10.17](https://github.com/amcharts/amcharts4/releases/tag/4.10.17).

## [4.10.17] - 2021-03-19

### Added
- New setting for `Export`: `webFontFilter`. Allows it to set to a regular expression. If set only those external fonts that their URL match regular exporession will be loaded.
- New setting for `ForceDirectedSeries`: `showOnTick` (default `10`). Render series hidden until Xth tick.
- New setting for `XYCursor`: `snapOnPan` (default `true`). Indicates whether to "snap" zoom selection to equal periods when panning by cursor ends.

### Fixed
- Zooming of chart with multiple vertical axes of which one was inverted was incorrect.
- `minZoomCount` was not being taken into account when zooming with mouse wheel.
- JSON config: `exporting.dataFields` setting was being ignored.
- Creating chart before its container is ready, was resulting in extra element in DOM in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
