### ISSUE TITLE
Slice Grouper plugin breaks when reset

### ISSUE THREAD

**Issue by runfaj** [amcharts/amcharts4#3297]
I think this is a bug unless there's something that needs to be added to the docs.

Here's a codepen. https://codepen.io/runfaj/pen/bGBBLpg The chart starts with the grouper plugin with a threshold of `10`. This works and shows 5 slices. However, as soon as you reset the chart and set a new threshold (`18` in the example when you hit the button), the chart/legend resets and shows all values instead of having the grouping applied (which is expected to show 3 slices). It almost appears as if, even though the series is reset, the plugin is cached elsewhere and breaks when re-adding.

amcharts version: happens on both 4.10.15 and 4.10.13
browser: any
os: any

**Comment by martynasma** [comment]
Why not just update threshold on existing grouper object and call `chart.invalidateData()`?

**Comment by runfaj** [comment]
@martynasma The main issue in our case is that the user is building chart options and data dynamically based on their selections, so when the chart is updated, some configurations might need to be removed, some data inputs may be completely different, etc. We found it was much more efficient to just reset the chart (overly simplified and replicated by the codepen), rather than trying to determine invalidation on data. This has worked very well for our many unique scenarios we've run into, but this plugin isn't playing nicely.

**Comment by runfaj** [comment]
@martynasma Checking in to see if you had any followup

**Comment by martynasma** [comment]
Not yet. I'll keep you posted tho.

**Comment by martynasma** [comment]
Fixed in [4.10.16](https://github.com/amcharts/amcharts4/releases/tag/4.10.16).

## [4.10.16] - 2021-03-03

### Fixed
- In some rare cases an critical error could happen on hoverable objects on touch-only displays.
- Zooming and drag-rotating a resized `MapChart` could throw off the map position.
- It was possible to continue zooming the chart using mouse wheel even when max zoom was reached.
- Zooming "inverted" horizontal axis was incorrect.
- Updating data on `SankeyDiagram` in some cases could result in an SO.
- `TreeMap` was showing incorrectly sized nodes with empty children array.
- Sometimes wrapping long strings were causing punctuation at the end of the word to wrap into the next line.
- Dynamically switching `logarithmic` setting for a `ValueAxis` was not updating its scale properly in some cases.
- `SliceGrouper` plugin was not updating properly when manipulating data and/or series.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by runfaj** [comment]
@martynasma This isn't completely resolved yet unfortunately. It works when just switching limit values or threshold values, but not when switching between the two types.
- In the original pen (https://codepen.io/runfaj/pen/bGBBLpg), I updated so you can see when the threshold gets to 40, the entire pie becomes grouped as expected.
- In this new pen (https://codepen.io/runfaj/pen/KKNBjRX), I have the limit and threshold switching. You can see when the threshold reaches that same 40, the grouping isn't present at all.

**Comment by martynasma** [comment]
In your pen when `type == "threshold"` you are setting `plugin.limit` to some non-existent variable `threshold`.

**Comment by runfaj** [comment]
> In your pen when `type == "threshold"` you are setting `plugin.limit` to some non-existent variable `threshold`.

🤦 whoops - thanks!

**Comment by Ices-Eyes** [comment]
I'm not sure I've correctly understand this bug, but is this still working?
I have a page where the graph is created once, with a grouper on the pieSeries. Based on user selections graph data are reloaded (just the data, series and chart remain) by chart.data=newData but after that the graph is updated but the grouper is lost; should it be updated in some way?
