### ISSUE TITLE
Question: Using amcharts4 with Jest

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#336]
We are using React and Jest in combination with amcharts4. Since Jest runs in Node it uses CommonJS modules and not standard ES Modules. However amcharts is using ES Modules, which leads to issues while testing components that import any module from amcharts.
What we currently do is manually override the `transformIgnorePatterns` from Jest that usually ignores everything from `node_modules` to not ignore amcharts. With that, amcharts gets transpiled as well and will run in the node environment for the Jest tests.

How do you propose to handle this situation? Do you have any (other) best practices in place for that?

**Comment by Pauan** [comment]
@Chnoch According to [the Jest docs](https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string) the recommendation is to change `transformIgnorePatterns` so that it will accept the AmCharts packages.

So it seems like your current setup is already correct.

**Comment by Under-Warz** [comment]
@Pauan @Chnoch any clue to make it working ? I'm trying everything and I always get error `SyntaxError: Unexpected token export`

Here is one of my test for `transformIgnorePatterns`

```
"transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.js"
    ],
```

**Comment by Under-Warz** [comment]
for futher readers, here is the working code with jest 

```
"transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.js$"
],
```

**Comment by mariadoesmath** [comment]
After overriding the `transformIgnorePatterns` configuration as shown above I'm still seeing the following error testing files that import amcharts. Am I missing something?

```
node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:2699
return [4 /*yield*/, import( /* webpackChunkName: "canvg" */"canvg")];
                     ^^^^^^
SyntaxError: Unexpected token import
```

**Comment by calaquend1** [comment]
> for futher readers, here is the working code with jest
> 
> ```
> "transformIgnorePatterns": [
>       "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.js$"
> ],
> ```

excuse me, where should I write this thing?
in package.json? 
or in package-lock.json?

**Comment by Under-Warz** [comment]
@calaquend1 it's configuration so in package.json ;)

**Comment by calaquend1** [comment]
@Under-Warz thank you, but it hadn't helped, can you look at this [question](https://stackoverflow.com/questions/55278206/jest-encountered-an-unexpected-token-when-import-new-libraries-in-react) on stackoverflow please?

**Comment by Fawwad-Khan** [comment]
@Under-Warz  I've been getting the same issue, regarding writing unit tests, is there any development on this?

**Comment by abhiisheek** [comment]
Install package `babel-jest-amcharts`

```
npm install --D babel-jest-amcharts
```

Add the following under `Jest` config:

```
"transform": {
  "^.+\\.(js|jsx)$": "babel-jest-amcharts"
},
"transformIgnorePatterns": [
  "[/\\\\]node_modules[/\\\\](?!(@amcharts)\\/).+\\.(js|jsx|ts|tsx)$"
]
```

This should solve the problem.

Here full working test example for reference: 

Test file
```
import React from "react";
import ReactDOM from "react-dom";
import { PieChart } from "@amcharts/amcharts4/charts";
import AmCharts4Wrapper from "./index";

class SVGPathElement extends HTMLElement {}

window.SVGPathElement = SVGPathElement;

describe("AmCharts4Wrapper", () => {
  const config = {
    series: [
      {
        type: "PieSeries",
        dataFields: {
          value: "litres",
          category: "country"
        }
      }
    ],
    data: [
      {
        country: "Lithuania",
        litres: 501.9
      },
      {
        country: "Czech Republic",
        litres: 301.9
      }
    ]
  };

  test("Whether it renders", () => {
    const div = document.createElement("div");
    document.body.appendChild(div);
    ReactDOM.render(
      <AmCharts4Wrapper
        config={config}
        id="amcharts-4"
        chartTypeClass={PieChart}
      />,
      div
    );
  });
});
```

> Note: AmCharts4Wrapper is a react component where Amcharts are used

**Comment by anand517** [comment]
Hi abhiisheek , I used this code in transform, transformIgnorePatterns of package.json still facing facing same issue.

**Comment by abhiisheek** [comment]
Hi @anand517 ,

You should be using the latest babel packages and plugins.

You can refer to this repo, which has working examples - https://github.com/abhiisheek/react-amcharts4.

**Comment by felipefedel** [comment]
I've followed all the steps but still having the problem. I cloned the https://github.com/abhiisheek/react-amcharts4 to use as an example but it's not working too. Could be another thing?
