### ISSUE TITLE
Why does zoom snap back to the right?

### ISSUE THREAD

**Issue by cowwoc** [amcharts/amcharts4#3381]
Testcase: https://codepen.io/cowwoc/pen/jOVdzKo

1. Zoom into the chart using the wheel mouse.
2. Drag the chart to the left, release mouse. Notice that the chart jumps to a different position on button release.

![screenshot2](https://user-images.githubusercontent.com/633348/111015867-cb984400-8378-11eb-97ac-a2e2a3dfcbbc.gif)

Is there a way to disable this behavior? I am expecting the chart position to remain unchanged when I release the mouse.

As a follow up question, in my real application the problem is much worse. I can pan to the right but not to the left. The chart keeps on jumping back to its initial position when the button is released. Here is a video of what I see:

![screenshot](https://user-images.githubusercontent.com/633348/111015818-a0adf000-8378-11eb-90c7-b8eb69550ea9.gif)

**Comment by cowwoc** [comment]
Is seems that there is always some level of "nudging back" going on when releasing the mouse button after panning but the amount of motion seems to grow noticeably the higher the zoom level. The more you zoom, the further away the position nudges back. My real application involves a very high level of zooming, which is why the nudge amount is so large.

1. Assuming this nudging behavior is as designed, the amount of nudging should take zooming into perspective to avoid jumping further out the more zoomed in you are.
2. We need a behavior to disable this behavior for people who don't want it.

**Comment by martynasma** [comment]
I'm afraid this is by design. We won't be able to change that. Sorry.

**Comment by cowwoc** [comment]
@martynasma Can you elaborate? What is the snap back trying to do? And why does the jump increase as the zoom level increases?

When I am fully zoomed out this behavior is unexpected but really not so bad. When I'm zoomed in, the chart becomes unusable :(

**Comment by martynasma** [comment]
The idea is that it snaps back to the nearest full periods on axis, so that chart looks tidy, not cut off in the middle.

We could consider a feature of disabling the snap back. Are you by any chance a paying customer? :)

**Comment by cowwoc** [comment]
> The idea is that it snaps back to the nearest full periods on axis, so that chart looks tidy, not cut off in the middle.

Yeah, I can kind of see that behavior in the first video but if you take a look at my second video I am releasing the mouse button closer to a point and a full period on the axis than before the mouse drag began. Are you seeing the same thing?

> We could consider a feature of disabling the snap back. Are you by any chance a paying customer? :)

Not yet. My product is not public yet. I plan to purchase a license once it is and, trust me, no one is more eager to get there than me :)

**Comment by martynasma** [comment]
Any chance you could whip up a runnable demo of the second chart? It doesn't look good indeed, but I'm having trouble reproducing it.

**Comment by cowwoc** [comment]
@martynasma Will do. Give me a couple of hours.

**Comment by cowwoc** [comment]
Okay, please try https://codepen.io/cowwoc/pen/QWGRjWg

Navigate to this exact point and zoom level:

![image](https://user-images.githubusercontent.com/633348/111422615-5654a800-86c5-11eb-8881-7dde01abd3f0.png)

Once the temperature axis on the left reaches 2-3 decimal places the chart will begin to exhibit the bug. Try panning to the left or right by dragging the chart and releasing the mouse. It should jump wildly in one direction but not the other.

Okay, so now some background information. My users need to visualize a lot of data with a high zoom level. I have 1 point every 10 seconds, across 12 months of data. When you zoom into one day's worth of data, I run into the following related problems:

1. It becomes very difficult to use the zoom scrollbar. The two knobs are extremely close together so you cannot choose between moving the viewport and changing the zoom level.
2. Panning jumps around controllably (the topic of this bug report).
3. When I am fully zoomed out, the chart renders multiple points stacked vertically on top of one another. The points fall outside the line chart. But when I zoom in the points suddenly move to their real position and fall on the line as expected.

Are you aware of the third issue, or should I try to provide a testcase for it?

**Comment by cowwoc** [comment]
Here is a better testcase: https://codepen.io/cowwoc/pen/ZEBNKPv

You can play with the value of `endDate` to get more or less data. My observations:

* I cannot chart 1 year worth of data. It takes 3 seconds to generate the input array. The chart prepares to render it for 30 seconds and then Chrome reports `Debugging connection was closed. Reason: Render process gone.`
* I reduce the time range to 3 months. It takes 500ms to generate the input array and 16 seconds to render. First question: extrapolating from this, it will probably take over 1 minute to render data for 1 year. Are there any tricks for optimize this so rendering begins within 2-3 seconds?
* Here is what the initial render looks like:

![image](https://user-images.githubusercontent.com/633348/111507153-b9275d00-8720-11eb-97ff-b9467ecbe890.png)

Right off the bat, the chart looks wrong. We are generating temperature values programmatically. The values rise and fall in a consistent manner but when you look at this chart it's implying that the values change non-deterministically over time.

The second thing to note is the temperature axis varies from 14.990 to 15.010. I will refer back to these values in a bit.

* Next, I zoom in until the grouping changes:

![image](https://user-images.githubusercontent.com/633348/111507598-3357e180-8721-11eb-93ae-5bc8c2ffefda.png)

Notice that the slope is even more erratic now and the temperature axis varies from 14.90 to 15.10.

* Again, I zoom in until the grouping changes:

![image](https://user-images.githubusercontent.com/633348/111507752-5e423580-8721-11eb-8b9a-203ae9939d3e.png)

Same problems.

* Again:

![image](https://user-images.githubusercontent.com/633348/111507875-79ad4080-8721-11eb-96a6-51e33ba3bd73.png)

Finally, the image looks right. Notice the temperature axis has even less precision (decimal places) now: 14.5 to 15.5.

* Again:
 
![image](https://user-images.githubusercontent.com/633348/111508070-aa8d7580-8721-11eb-90eb-c544f121760b.png)

The slope is wrong again. The temperature axis has even less precision. And finally, at *this* level of zooming we notice two new things:

1. The scrollbar at the top looks like one knob so it's no longer usable.
2. Dragging the chart a little to the left or right triggers massive jumps to the right (never to the left).

I hope the above screenshots help you to reproduce this on your end.

**Comment by martynasma** [comment]
Thanks for such in-depth details.

OK, so we're looking at this from two angles:

1) We're going to introduce a setting to completely disable snapping.
2) We're looking at ways to fix the snapping in overzoom.

Will keep you posted.

**Comment by martynasma** [comment]
Fixed in [4.10.17](https://github.com/amcharts/amcharts4/releases/tag/4.10.17).

## [4.10.17] - 2021-03-19

### Added
- New setting for `Export`: `webFontFilter`. Allows it to set to a regular expression. If set only those external fonts that their URL match regular exporession will be loaded.
- New setting for `ForceDirectedSeries`: `showOnTick` (default `10`). Render series hidden until Xth tick.
- New setting for `XYCursor`: `snapOnPan` (default `true`). Indicates whether to "snap" zoom selection to equal periods when panning by cursor ends.

### Fixed
- Zooming of chart with multiple vertical axes of which one was inverted was incorrect.
- `minZoomCount` was not being taken into account when zooming with mouse wheel.
- JSON config: `exporting.dataFields` setting was being ignored.
- Creating chart before its container is ready, was resulting in extra element in DOM in some cases.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by cowwoc** [comment]
@martynasma I just tested 4.10.17.

The situation is much better in the sense that I am no longer thrown to the right when I try to move to the left, but I am still unable to move to the left.

I zoom a lot, then:

1. If I LMB click, drag the chart to the left, release, then the chart scrolls to the right.
2. If I LMB click, drag the chart to the right, release, then the chart pushes me back to the original position before I LMB clicked.

I am expecting case 2 to behave the same as case 1. I should be able to move to the left. Are you able to reproduce this on your end?

On a related note, how can I update the testcase to use 4.10.17? I tried updating the links to

```
<script src="//cdn.amcharts.com/lib/4/core.js"></script>
<script src="//cdn.amcharts.com/lib/4/charts.js"></script>
<script src="//cdn.amcharts.com/lib/4/themes/animated.js"></script>
<div id="chart"></div>
```

but I am seeing the old jumpy behavior when I zoom. I'm guessing the old version is being used.

**Comment by cowwoc** [comment]
I finally understand what is going on.

The horizontal space is divided into cells (as outlined by the grid lines):

![image](https://user-images.githubusercontent.com/633348/111844501-896f8500-88d9-11eb-95a4-1e38ee8970a0.png)

In the left-most cell, we have 2 points. If the user drags the chart to the left and releases the mouse, the chart will try to re-align itself along grid lines so that the left-most boundary corresponds to the beginning of a cell.

If you drag the length of exactly one cell and release the mouse, the chart will retain its position. If you drag less than one cell, the chart will jump left (always left!) to align itself with the cell boundary.

This means that if you drag left to the middle of a cell, the chart will jump left to correct the problem. If you drag right, it will again jump left to correct the problem.

So my suggestion: note whether the user is dragging left or right. If you have to snap back, please snap back in the opposite direction. Meaning, if the user was dragging left then you should jump back to the right. If the user was dragging right then you should jump back to the left.

This should correct the problem once and for all.

**Comment by martynasma** [comment]
You're right about the assessment. However, we're not planning on changing this behavior just yet. Sorry.

I suppose you can use the new setting to disable snapping altogether.

**Comment by cowwoc** [comment]
@martynasma Okay, I'll disable it for now. Thanks.

**Comment by cowwoc** [comment]
@martynasma What about the fact that the chart does not match the expected shape when it is zoomed out? Meaning the data reflects a consistent rise and fall but when we're zoomed out we see irregular shapes instead.

**Comment by martynasma** [comment]
Let's keep this place clutter-free, both for our own sake and the other's. If you have other questions, not directly related to original topic, please post a separate issue.

**Comment by cowwoc** [comment]
@martynasma Agreed. Posted as https://github.com/amcharts/amcharts4/issues/3400
