### ISSUE TITLE
Updating stack chart w/animations can leave chart in "zoomed" state

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#55]
I'm seeing an issue with stacked charts that occurs when animations are enabled and the chart's data is updated. Sometimes after the chart is updated, the chart ends up in a pseudo "zoomed" state. I see the zoom out button, but clicking the button doesn't do anything. Also, not all of the chart is showing up.

Here's an example of the problem:
https://codepen.io/anon/pen/MXwrOe

Try clicking the "Update" button. You may have to click it several times in order to see the behavior.

It's pretty easy to recreate using Firefox, but it rarely happens in Chrome. 

The problem does appear to be tied to the animation speed. If I slow down the animations, it happens way less frequently (if I slow it back down to the original 1.4 animation speeds, it doesn't seem to happen at all.)

**Comment by dswitzer** [comment]
I should add, I also see this sometimes when rendering the initial chart. It really seems to be impacted when there are lots of charts on the page.

**Comment by zeroin** [comment]
I found a problem and it will be fixed in next update. By the way, if your data count doesn't change,  instead of changing whole data you you could actually change values in original data provider and then call chart.invalidateRawData() this will make the bars to animate from old values to new ones. (This won't solve this issue in current release, but will work fine in next update).

**Comment by martynasma** [comment]
Solved in [4.0.0-beta.28](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.28) ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta28---2018-06-05)).

**Comment by dswitzer** [comment]
I'm still seeing this problem—even [my codepen example above](https://codepen.io/anon/pen/MXwrOe) is still exhibiting the behavior.

It definitely seems to be better, but it's still happening.

NOTE: In my test page I have 8 different charts on a page. The problem seems to be compounded for each chart on the page. It's like the more animations going on, the more likely things are to get out of sync.

**Comment by martynasma** [comment]
I can't seem to be able to reproduce it.

(clicked like a thousand times on the Update)

Can you try clearing your browser cache and trying again?

**Comment by dswitzer** [comment]
I can't recreate it in Chrome now, but it does happen pretty consistently within the first few clicks using Firefox 60.0.1.

**Comment by martynasma** [comment]
OK, just pressed another thousand times on "Update" on Firefox 60.0.1 :)

Still can't make it stay in zoomed state.

I have to repeat my mantra: have you tried clearing browser cache in Firefox? :)

**Comment by dswitzer** [comment]
@martynasma,

Thanks for following up. Nothing worse than trying to troubleshoot those "works for me" issues!!!

My Firefox cache is definitely cleared (I have it set to never cache in both normal mode and when Dev Tools are open, and I've confirmed I'm seeing a 200 HTTP status code when loading the JS).

I'm not sure how your infrastructure is set up, but if you're using a distributed caching service like Cloudfront, it's always possible the server I'm connecting to is getting an older version of the core.js or charts.js file.

Is there a way to get the current build/revision from the API?

I looked through the am4core and am4chart objects, but didn't see anything that appeared to return a version. I even checked some API calls like am4core.getSystem().

Here's a screen capture showing it happening. 

![amcharts_firefox_update_bug](https://user-images.githubusercontent.com/900497/41037262-cc9fcef2-6960-11e8-89fe-b5050e755f15.gif)

I've got the Dev Tools open so you can see the 200 HTTP status code. All I did was reload the page, scroll the network results so that the amCharts files were in view and then clicked the "Update" button. This was the first time I clicked the "Update" button. As you can see, it happened on the first try. I could actually zoom out the first time I clicked "Update", but you'll notice the second time I clicked the button the zoom out button doesn't work. You can see me clicking it but it doesn't zoom out.

**Comment by martynasma** [comment]
We do use a cloud front for our CDN-served libraries.

However, it's set up to clear all its caches any time we post a new version.

Just to be supersure you're not using cached version, try adding gibberish `?32132` parameter to our .js includes.

Also, to check current version, run this in console:

```
am4core.System.VERSION
```

**Comment by dswitzer** [comment]
It's showing "4.0.0-beta.28" for the version, so it's definitely the latest. Behavior is the same.

**Comment by martynasma** [comment]
OK, thanks for checking.

We'll do some more testing.

**Comment by dswitzer** [comment]
Let me know if there's anything you need from me.

**Comment by martynasma** [comment]
Hey, can you check if you can still reproduce this?

I've clicked update, like a half a million of times, never got a single zoom misfire.

Using FireFox.

**Comment by dswitzer** [comment]
No, I can no longer replicate the behavior so it looks like the bug has been resolved!
