### ISSUE TITLE
Can't create the chart again after dispose()

### ISSUE THREAD

**Issue by sersh88** [amcharts/amcharts4#65]
I use charts as React component. When component going to unmount I call `chart.dispose()` as in [docs page](https://www.amcharts.com/docs/v4/getting-started/integrations/using-react/)

After unmounting chart component I get error:

```
Uncaught Error: EventDispatcher is disposed
    at SpriteEventDispatcher.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js.EventDispatcher.isEnabled (EventDispatcher.js:163)
    at Container.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js.Sprite.setPropertyValue (Sprite.js:2829)
    at Container.set [as maxWidth] (Container.js:312)
    at SVGContainer.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/rendering/SVGContainer.js.SVGContainer.measure (SVGContainer.js:76)
    at System.js:362
    at Object.each [as c] (Array.js:54)
    at System.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/System.js.System.measure (System.js:360)
    at System.webpackJsonp../node_modules/@amcharts/amcharts4/.internal/core/System.js.System.update (System.js:134)
    at System.js:294
```

And if component mounted again I see blank chart and no errors in console.
version: beta28

**Comment by Pauan** [comment]
@sersh88 Could you please share your code that you are using to create your chart?

**Comment by sersh88** [comment]
Here is the example code to reproduce this error:
https://github.com/sersh88/amcharts-dispose-issue
Clicking on hide/show will broke the chart and you will see `EventDispatcher is disposed` errors in console.

**Comment by Pauan** [comment]
@sersh88 Thanks a lot! That's very helpful.

We've fixed this issue, it'll be in the next release (which isn't released yet). We'll let you know when it's released.

**Comment by sersh88** [comment]
@Pauan 
Thank you!

**Comment by martynasma** [comment]
Fixed in 4.0.0-beta.30. ([changelog](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md#400-beta30---2018-06-22))

**Comment by arm1n** [comment]
Hey guys, sorry for the late response on this one. I just wanted to come back to you to tell you that latest beta `4.0.0-beta.30` does *not* resolve the issue for me (unlike mentioned in #106). I'm still getting `Uncaught Error: EventDispatcher is disposed` error :(

Is there something wrong with my setup? I'm following the instructions from the docs with this destruction code in my component: 

```javascript
public ngOnDestroy(): void {
  this._zone.runOutsideAngular(
    this._destroy.bind(this)
  );
}

private _destroy(): void {
  if (this._chart !== null) {
    this._chart.dispose();
    this._chart = null;
  }
}
```

Avoiding the dispose call brings up issue #48, so I'm stuck what to do here. Any help is highly appreciated, cause I really want to use the library in production soon. Thanks!

**Comment by arm1n** [comment]
It's me again - turned out that I had a caching issue in my docker container so that it pulled an old version, now being on `4.0.0-beta.30` and the `dispose()` issue has gone :) So ignore my previous comment - good work!

**Comment by Pauan** [comment]
Phew, I was getting a bit worried there. I'm glad that everything works now!

**Comment by peluprvi** [comment]
It still have some error here when using more than one chart per page.
It can be the way I'm loading the chart.
I already update the version and followed the idea of using external variable to dispose the chart.

I created a base that you can download and edit to test it https://codesandbox.io/s/828rxoq2lj

**Comment by Pauan** [comment]
@peluprvi Thanks for taking the time to make that, but when I tried downloading it and building it, I get weird errors:

```
Plugin/Preset files are not allowed to export objects, only functions. In node_modules\babel-preset-stage-2\lib\index.js
```

And unfortunately codesandbox also gives weird errors:

```
/node_modules/@amcharts/amcharts4/.internal/core/export/Export.js: Unexpected token (2298:49)
```

I don't think these errors are caused by amCharts.

**Comment by peluprvi** [comment]
@Pauan Sorry, I was without time to test it. It was only a base to create a project using @vue/cli 3 and copy the components and views. Anyway... I had some time today and I created a repository that you can test: https://github.com/peluprvi/vue-amcharts4-teste

You can `npm install` and `npm run serve`
or
`yarn` and `yarn serve` (I'm using yarn.)

You can see some console errors when routing. And you can also test other things on that base (such as load/rendering time).

Please feel free to contact me if you have any trouble and let me know how I can better help you find out these issues.

PS: I will edit all places that I pointed to codesendbox to that repository.

**Comment by Pauan** [comment]
@peluprvi Thanks a lot! That's very helpful. When I switch charts, everything seems fine. But when I switch between the charts very quickly, then the error happens. I'll investigate this and report back to you after I've fixed the problem.

**Comment by peluprvi** [comment]
I think it only happens when the page has 2 charts and you switch to another one.

**Comment by peluprvi** [comment]
Since I can't use `this.chart` with [the memory issue](https://github.com/amcharts/amcharts4/issues/106), to dispose the chart in Vue I created this workaround: https://github.com/peluprvi/vue-amcharts4-teste/commit/23a09ef6b7dc14c499b75971e72da55c04cbf859

**Comment by Pauan** [comment]
@peluprvi I've spent the past couple weeks fixing dozens of disposer leaks, and I think I fixed the problem.

Upgrade to version `4.0.0-beta.36 `, and also make these changes to your app code:

```js
<template>
  <div
    ref="chartdiv"
    class="chart"
  />
</template>

<script>
import * as am4core from '@amcharts/amcharts4/core'
import * as am4charts from '@amcharts/amcharts4/charts'

export default {
  name: 'Chart',

  props: {
    data: {
      type: Array,
      default () {
        return []
      }
    }
  },

  beforeDestroy () {
    this.chart && this.chart.dispose()
  },

  mounted () {
    const chart = am4core.create(this.$refs.chartdiv, am4charts.XYChart)

    chart.paddingTop = 0
    chart.paddingRight = 0
    chart.paddingBottom = 0
    chart.paddingLeft = 0

    let max = 1
    chart.data = this.data.map((data, index) => {
      max = data > max ? data : max
      return {
        column: index,
        value: data
      }
    })

    let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis())
    categoryAxis.renderer.disabled = true
    categoryAxis.renderer.grid.template.location = 0
    categoryAxis.renderer.grid.template.strokeOpacity = 0
    categoryAxis.renderer.ticks.template.disabled = true
    categoryAxis.dataFields.category = 'column'

    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis())
    valueAxis.renderer.disabled = true
    valueAxis.renderer.grid.template.location = 0
    valueAxis.renderer.grid.template.strokeOpacity = 0
    valueAxis.renderer.ticks.template.disabled = true
    valueAxis.tooltip.disabled = true
    valueAxis.min = 0
    valueAxis.max = max
    valueAxis.strictMinMax = true

    let series = chart.series.push(new am4charts.ColumnSeries())
    series.dataFields.categoryX = 'column'
    series.dataFields.valueY = 'value'
    series.stroke = am4core.color('#3F51B5')
    series.fill = am4core.color('#3F51B5')

    this.chart = chart
  }
}
</script>

<style scoped>
.chart {
  height: 180px;
  width: 320px;
}
</style>
```

(It uses `this.chart` rather than a top-level `chart` variable).

**Comment by lttien1** [comment]
@pauan 

I downloaded the latest version. And this issue still is here.

**Comment by Pauan** [comment]
@lttien1 Could you please file a new issue and provide as much information as possible (amCharts version, your code, etc.)?

**Comment by lttien1** [comment]
@Pauan 
I implemented amcharts library for my React project and I have about six chart on same page.
I use 4.2.1 and this issue still happens. I try to downgrade 4.0.0-beta.36 and this issue have fixed. Please check it again. If you cannot reproduce this issue in 4.2.1 please say to me and I send my code to you. 
In addition, because I have multiple charts on same page so browser will freeze after about 15 minutes using. And i check task manager of Chrome and I see that my website run with > 1GB memory and It is increasing faster. Thanks you for your reply

**Comment by Pauan** [comment]
@lttien1 I tried using `create-react-app` to create 6 charts:

```js
class App extends Component {
  makeChart(name) {
    let chart = am4core.create(name, am4charts.XYChart);

    chart.paddingRight = 20;

    let data = [];
    let visits = 10;
    for (let i = 1; i < 366; i++) {
      visits += Math.round((Math.random() < 0.5 ? 1 : -1) * Math.random() * 10);
      data.push({ date: new Date(2018, 0, i), name: "name" + i, value: visits });
    }

    chart.data = data;

    let dateAxis = chart.xAxes.push(new am4charts.DateAxis());
    dateAxis.renderer.grid.template.location = 0;

    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.tooltip.disabled = true;
    valueAxis.renderer.minWidth = 35;

    let series = chart.series.push(new am4charts.LineSeries());
    series.dataFields.dateX = "date";
    series.dataFields.valueY = "value";

    series.tooltipText = "{valueY.value}";
    chart.cursor = new am4charts.XYCursor();

    let scrollbarX = new am4charts.XYChartScrollbar();
    scrollbarX.series.push(series);
    chart.scrollbarX = scrollbarX;

    return chart;
  }

  componentDidMount() {
    this.charts = [
      this.makeChart("chartdiv1"),
      this.makeChart("chartdiv2"),
      this.makeChart("chartdiv3"),
      this.makeChart("chartdiv4"),
      this.makeChart("chartdiv5"),
      this.makeChart("chartdiv6")
    ];
  }

  componentWillUnmount() {
    if (this.charts) {
      this.charts.forEach((chart) => chart.dispose());
    }
  }

  render() {
    return (
      <div>
        <div id="chartdiv1" style={{ width: "100%", height: "500px" }}></div>
        <div id="chartdiv2" style={{ width: "100%", height: "500px" }}></div>
        <div id="chartdiv3" style={{ width: "100%", height: "500px" }}></div>
        <div id="chartdiv4" style={{ width: "100%", height: "500px" }}></div>
        <div id="chartdiv5" style={{ width: "100%", height: "500px" }}></div>
        <div id="chartdiv6" style={{ width: "100%", height: "500px" }}></div>
       </div>
    );
  }
}
```

It seems to work okay, no errors, and no memory leak.

Are you sure that you are giving each chart a unique id, and that you are properly calling `dispose()` inside of `componentWillUnmount`? You *must* call `dispose` for every chart.

If you still cannot fix it, please send me your code. You can send it in a `.zip` file to pcxunlimited@gmail.com

**Comment by Pauan** [comment]
Also, please try upgrading to amCharts version `4.3.2`, we've fixed some bugs since then.

**Comment by wrightdaniel2017** [comment]
May not be the best answer but I just added:

document.getElementById("wordCloudBody").innerHTML = `<div id="chartdiv"></div>`;

to clear my chart and still keep the chartdiv element available to load a new chart.... works for now... still probably not hte best answer
