### ISSUE TITLE
Labels following pointer are initially rendered at top/left

### ISSUE THREAD

**Issue by dswitzer** [amcharts/amcharts4#66]
When using the `tooltipPosition = "pointer"` option on a series so that the tooltip follows the pointer, the tooltip is initially being rendered at the top/left. 

I only visually notice the problem when using Firefox.

Here's an example that shows the issue:
https://codepen.io/anon/pen/GGWLBa

If you watch carefully, on the first mouse over of each series you can see the tooltip flash over the "Seven" label.

What I've observed is that when there are lots of charts, the positioning is much slower, so the mis-positioned tooltip becomes much more noticeable.

Here's what I'm seeing in our application. You'll notice that as I mouse over the data, the tooltip will show up in the top/left. (NOTE: The video dropped some frames, so you don't always see it, but you it does illustrate the issue when mousing over the "Under SLA" and "No SLA").

![amcharts4_tooltip_positioning_issue](https://user-images.githubusercontent.com/900497/41260364-240b54fc-6da5-11e8-8535-8d8bffd08e49.gif)

**Comment by martynasma** [comment]
Confirmed. I was able to reproduce this in Firefox as well.

Reduction of tooltip performance with multiple charts is a separate issue, we might need to tackle as well. I think I know where the bottle necks might be coming from.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.31](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.31).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
I'm still seeing the same behavior. Confirmed I'm using 4.0.0-beta.31.

If you look at the example again, you can see the version number at the top of the page. The labels are still rendering in the top/left in Firefox initially.

**Comment by martynasma** [comment]
I can now make the tooltip appear in top-left only when chart is initially animating.

Can you confirm if that is the case for you as well, or if you can make the issue appear when chart is static, too?

**Comment by dswitzer** [comment]
It definitely happens with static charts, because I'm not using animations in our app. Maybe it's not noticeable w/out animations and you only have 1 chart, but I can definitely still see the behavior with static charts.

**Comment by martynasma** [comment]
Does this happen on the codepen demo you posted? Or should we try to whip up something closer to your setup? (multiple small charts)

**Comment by martynasma** [comment]
Thanks for checking.

We'll need to do some more testing then.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.45](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.45).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

## [4.0.0-beta.45] - 2018-08-17

### Added
- New hardcoded `Sprite` state name added `"hoverActive"` which (if defined) is applied on active elements on hover. This state is applied last in the chain.
- New property on `DataSource`: `keepCount`. If set to `true` incremental updates will remove data items from the beginning of the current dataset, when adding the newly-loaded ones.
- New property on `DataSource`: `incrementalParams`. It's an object whose key/value pairs will be added to URL as parameters when DataSource is making an incremental load request.
- `Popup` (and `Modal`) now have an event dispatcher (`events`) with two events: `"opened"` and `"closed"`. ([more info](https://www.amcharts.com/docs/v4/concepts/popups-and-modals/#Event_handlers))

### Changed
- Legend now respects `itemContainers.template.togglable = false`, which disables default functionality of toggling items when clicked in legend, allowing users to attach their own funcitonality to legend item clicks.
- Toggling of items in Legend can now be disabled by setting `chart.legend.itemContainers.template.togglable = false`.
- In `XYChart` with a `DateAxis`, cursor and data at irregular intervals will now display a Tooltip for nearest available series' data item.
- `zoomToCategories` method of `CategoryAxis` now zooms to the end of the "to" category.
- Default `urlTarget` of amCharts logo is now `"_blank"`.

### Fixed
- In `DataSource` the formatters `inputDateFormat` was ignored.
- Incremental data load via `DataSource` was not working.
- Tooltip used to flicker ar 0,0 position in some cases when hovering over elements.
- Fixed issue which caused chart to gradually shrink to invisibility under some conditions.
- Fixed rendering errors for charts that were initialized in hidden containers.
- `XYCursor` lines and axis tooltips were not shown if chart did not have any data (data was set directly on axis/series).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

**Comment by dswitzer** [comment]
I'm still seeing this behavior using beta 46, at least in Firefox which was the first browser I tested. The original demo I posted still shows the behavior. You can see it's using beta 46, because it shows the version in the upper left.

When I mouse over any chart I see a quick flash of the tooltop at 0,0.

**Comment by martynasma** [comment]
Ah jee, tough one to crack. Back at it.

Sorry for the back and forth :/

**Comment by dswitzer** [comment]
FYI - Still broken in beta 48.

**Comment by martynasma** [comment]
@dswitzer We can't reproduce this anymore. Can you try it on your end with beta.49 and latest FF?

**Comment by dswitzer** [comment]
@martynasma,

Good work! It appears to be resolved in beta 51.

**Comment by dswitzer** [comment]
After so more testing, this is still happening in Edge and IE11. It doesn't seem to happen if the the "animation" theme is used, but if the standard theme is used, I see a quick flashing in Edge/IE11.

Here's the same example above, but with animations disabled:

https://codepen.io/anon/pen/ZMNRLB

**Comment by martynasma** [comment]
Indeed. This one is one tough nut :)

**Comment by martynasma** [comment]
Fixed/implemented in [4.0.0-beta.61](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.61).

## [4.0.0-beta.61] - 2018-10-19

### Changed
- If element has `url` set, when clicked, it will now parse for data placeholders in curcly brackets, e.g. `"{category}"` allowing have dynamic data-driven URLs. Note, the elements are not url-encoded so you need to specify encoding manually, e.g.: `series.columns.template.url = "https://www.google.com/search?q={category.urlEncode()}";`.

### Fixed
- `Label.fullWords = false` was not working properly.
- `AxisLabelCircular` was positioning labels incorrectly, if label.radius was negative (since 59).
- `"grid"` layout in `Container` was incorrectly layouting elements if their `width` was set in percent.
- [IE] Multi-line truncated labels were not working properly on IE.
- [IE] was incorrectly zIndexing elemens (since version 56).
- [IE] tooltip initial flicker solved.
- [IE] was incorrectly sorting multiple series tooltips (if `Cursor` was used).

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by dswitzer** [comment]
I've confirmed that this has been fixed. Tested w/beta 70.
