### ISSUE TITLE
XYCursor prevents tooltips from appearing on Gantt chart

### ISSUE THREAD

**Issue by FrankMerema** [amcharts/amcharts4#668]
Hi,

First of all I don't know if I'm doing things wrong or misunderstand, but hopefully you guys can help me.

Currently I work on a Gantt chart with dates, which looks like the one on the the amcharts site.
The request came to show labels (bulletLabels) on each item representing the title. Beside that it should show a tooltip on hovering, stating title and time slot.
When I tried to add the labels, suddenly the tooltips would not show anymore on hovering over an item because the labels are almost as big as the complete box. So it looks like hovering over the label is not triggering the tooltip anymore, and if you hover besides the label it will show again.

I made a code pen based on the gantt example on the site, which shows this issue.
Try to hover over the boxes, which will show the tooltip unless you hover over the labes within the boxes.

https://codepen.io/anon/pen/vvOPgO?editors=0010

Hopefully somebody can help me with this issue!

**Comment by FrankMerema** [comment]
Unfortunately this didn't do the trick :(

I updated the code pen with the suggested line. But still hovering on the labels is not showing the tooltip.

**Comment by FrankMerema** [comment]
Sorry was a bug on my site, where this didn't get triggered. Thanks!

**Comment by FrankMerema** [comment]
I found an other issue, together with the XYCursor enabled. 
In the code pen I just added an XYCursor and suddenly the tooltips wont work at all anymore. 

And I see some other weird things happening on the date axis tooltip, but maybe that's an other question.

Hopefully you have an answer for this as well :)

**Comment by zeroin** [comment]
We addded `cursorTooltipEnabled` property to XYSeries (available in next release). You should set it to `false` in order columns tooltips to be properly shown.

**Comment by martynasma** [comment]
Fixed in [4.0.11](https://github.com/amcharts/amcharts4/releases/tag/4.0.11).

## [4.0.11] - 2018-12-24

### Added
- `"disabled"` and `"enabled"` events added to `Sprite`.
- `cursorTooltipEnabled` added to `XYSeries`  If set to `false` cursor will not trigger bullet/item tooltips on series.

### Changed
- IMPORTANT (CODE-BREAKING CHANGES) For performance reasons we no longer create axis elements if they are disabled. For the same reasons we disabled by `axis.ticks` and `axis.axisFills` by default. Previously to enable them you had to set their `strokeOpacity` and/or `fillOpacity` to non-zero. This no longer will work. You will need to set `disabled` to `false` instead.
- `axisRanges` now take their default values from `dateAxis.axisRanges.template` items (`axisFill`, `grid`, `tick`, `label`). Previously they were using the defaults from `dateAxis.renderer.label` etc. This was not comfortable and counter-intuitive.

### Fixed
- `XYChartScrollbar`'s value axis was calculating `min`/`max` with a very big step.
- Ember plugin was throwing console errors.
- Fixed occasional zoom-in issue on Mobile Safari.
- `MapChart` mouse wheel zoom direction was inverted on some browsers.
- Cursor was not snapping correctly to `DateAxis` items.
- Multiple floating columns on the same category were disappearing when scrolling the chart.
- Date range fills were off when zooming on Gantt Chart.
- Overlapping tooltips problem solved.
- When `snapToSeries` was set for a tooltip, it was flickering a lot on slower browsers.
- `alignLabels = false` on a `PieSeries3D` was causing labels to be positioned incorrectly.
- `PieSeries.dataFields.radiusValue` was not accounting for `chart.innerRadius`.
- Dynamically updating `alignLabels` for `PieSeries` did not work correctly.
- Legend: `itemValueText` only worked if `valueText` was set.
- `ValueAxis` setting `maxZoomFactor = 1` was not working as expected.
- Changing values for all data items sometimes was resulting in `ValueAxis` scale going into negative.
- Some more tooltip and cursor related issues fixed.
- Axis Fill did not properly fill the whole span when axis was scaled.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by bmampaey** [comment]
I think I don't understand exactly how to have column tooltip on a Gantt chart AND a cursor.

I tried setting `series1.cursorTooltipEnabled = false; ` but it still does not show the tooltips on the columns (or very briefly).

I modified the codepen of the Gantt Chart from the demos archive and added at the end:

```
// Add cursor
chart.cursor = new am4charts.XYCursor();

// Set cursorTooltipEnabled to false on series
series1.cursorTooltipEnabled = false;
```

See https://codepen.io/Benjamin-Mampaey/pen/KJrZeO
