### ISSUE TITLE
zoomXY chart cursor behavior with DateAxis is broken

### ISSUE THREAD

**Issue by Achilles1515** [amcharts/amcharts4#721]
This issue might be best represented by looking at the gifs on the [Chart Cursor docs page](https://www.amcharts.com/docs/v4/concepts/chart-cursor/#Zooming_panning) showing the different `chart.cursor.behavior` options.

zoomX and zoomY make sense to me, but zoomXY does not. 

Here are the gifs from the docs page:

--------
"zoomX" - Zooms all horizontal axes

![zoomx](https://user-images.githubusercontent.com/23387905/50247154-1a76ef00-03a5-11e9-9b9b-229e990f6cbe.gif)

--------
"zoomY" - Zooms all vertical axes

![zoomy](https://user-images.githubusercontent.com/23387905/50247246-5e69f400-03a5-11e9-8c2b-00e2accd6b41.gif)

--------
"zoomXY" - Zooms both horizontal and vertical axes

![zoomxy](https://user-images.githubusercontent.com/23387905/50247251-6164e480-03a5-11e9-8521-c713a63a47a1.gif)

--------

Again, zoomX and zoomY seem to work as expected and zooms the chart to the boundaries of your selection. For zoomXY, the zoomX portion seems to work, but the zoomY just doesn't. In the gif above, the zoomXY selection by the user explicitly excludes all the data from the lowest series, yet it still shows up in the chart after the zoom. In fact, looking at the final zoom results of the zoomX gif and the zoomXY gif look almost identical!

Here is another gif to disect of me trying to zoom in on a specific portion of the chart. After the first zoom, all the data series are shown despite my zoom not including points from two of the lines (turquoise and pink). Then on my second zoom attempt, it "successfully" performs the zoomY as I wanted (not showing the data from the two lines mentioned above), but for some reason the area I zoomed is pushed all the way to the left of the chart...?

![test](https://user-images.githubusercontent.com/23387905/50248625-a68b1580-03a9-11e9-9f92-1252ef3691bd.gif)

**Comment by Achilles1515** [comment]
EDIT:
I believe the behavior seen above only happens when using a DateAxis.
Here is the same CodePen from the gif above, but with a ValueAxis used for the x-axis instead of a DateAxis.

https://codepen.io/anon/pen/REKwzB

zoomXY now works just as expected.

Title of this issue has been changed.

**Comment by martynasma** [comment]
Indeed. Looks like "Y" part of the "zoomXY" does not work properly.

**Comment by jimmykane** [comment]
Same issue here .

**Comment by zeroin** [comment]
Well, this is by design. When zooming date axis we check min and max of zoomed-in section and update value axis accordingly. We will consider adding a possibility to disable this behavior.

**Comment by Achilles1515** [comment]
> Well, this is by design. When zooming date axis we check min and max of zoomed-in section and update value axis accordingly. We will consider adding a possibility to disable this behavior.

I'm confused by this comment. Say I have a chart with multiple series and I make a zoomXY selection that only encapsulates data from one series. Are you saying that the code looks at the min and max date of the zoom box, then **ignores** the min and max **value axis** component of the zoom box and just fits all the data from all the series into view...despite the selection only containing a single series? Isn't this the same functionality as zoomX and what is the reasoning behind the design decision to purposefully ignore the value axis component of a zoomXY selection box for a DateAxis?

But this doesn't even make sense with the last gif I posted where I make, for all intents and purposes, two identical zooms, but only on the second zoom does it actually honor the value-axis component of the selection box. Can you explain, in reference to your comment, what is happening on each of the zoom selections in the gif and why the final states are so? Also, why does the result of the second zoom show the data points on the left side of the chart, rather than the ~center (which is where the points were in the zoom selection box)?

**Comment by martynasma** [comment]
Let me clarify it.

This is due to a fuzzy logic that works for `DateAxis` + `ValueAxis` duo setups. Basically, zooming a horizontal date range kicks in behavior that determines visible value range to encapsulate range from **all series**.

The same mechanism kicks in, for example, when you pan the chart.

Just to make it super clear, we're not saying it's undisputedly right. We're saying that we will do our best to make this behavior configurable, which would enable true XY zooming on Date/Value axis setups.

In any case, when that is implemented, we'll let you all know here.

Thanks for the patience!

**Comment by Achilles1515** [comment]
@martynasma Thanks for some more explanation.
If what you said is true (about encapsulating range from all series), then in the last gif in my original post, why am I able to zoom in to a region that **doesn't** include two of the line series after the second zoom attempt?

**Comment by martynasma** [comment]
Frankly, I'm not entirely sure :)

Let's shelve this until we can have a proper look inside this.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.

**Comment by sfelim** [comment]
@martynasma I still have the same problem.
Here is a gif that illustrates the problem. In which version did you fix this issue?

Thanks.

![zoomXY-AmCharts](https://user-images.githubusercontent.com/40490841/73025636-f08cc900-3dfd-11ea-855b-f6a3463b8175.gif)

**Comment by sunith-kumar** [comment]
@martynasma I am still facing this Issue, Would be great if you can let us know the build version that fixed this Issue

Thanks

**Comment by zeroin** [comment]
So this can be actually solved if you remove `selectionextremeschanged` listener:

`series.events.off("selectionextremeschanged", valueAxis.handleSelectionExtremesChange, valueAxis, false)`

Like in this demo:
https://codepen.io/team/amcharts/pen/BaoYydK

Note, this means that when zooming the chart with the scrollbar the chart will keep the selection and will not adjust value axis to fit the selection into it, but there is no way to overcome this.
