### ISSUE TITLE
LineSeries inside scrollbar disappears after invalidateData()

### ISSUE THREAD

**Issue by RobbiesCode** [amcharts/amcharts4#826]
I am working on the same demo as https://github.com/amcharts/amcharts4/issues/823. A simple line chart.

When I loop over `chart.data` to add some extra fields (used as a series' bullet `configField`) and then call `invalidateData()`, the line series inside `chart.scrollbar` disappears. (Unwanted side-effect).

![image](https://user-images.githubusercontent.com/13300227/51182159-96ddee80-18cd-11e9-91ec-cd7ece997c85.png)
_Line Series inside scrollbar is gone._

HTML file: [linechart4.zip](https://github.com/amcharts/amcharts4/files/2759705/linechart4.zip)

**Comment by martynasma** [comment]
How about using regular `Sprite` for bullet and setting its `path` property to an SVG path?

**Comment by CalvinNunes** [comment]
I have the same issue.

There's a moment in my chart where the user clicks on a bullet (for example), and then there's a callback that changes many properties inside the data. When I call `validateData()` or `invalidateData()` the lineSeries inside the XYScrollbar disappears... (AmCharts4)

**Comment by martynasma** [comment]
Simple test case for dev team:
https://codepen.io/team/amcharts/pen/4b8ab4a051b3d3aaff5a8acc84068f60?editors=0100

**Comment by dFelinger** [comment]
Is there any solution until the bug is not fixed.

**Comment by martynasma** [comment]
This seems to have been fixed already. Closing.

**Comment by jbate** [comment]
@martynasma the bug in the test case still appears present for this: https://codepen.io/team/amcharts/pen/4b8ab4a051b3d3aaff5a8acc84068f60?editors=0100

Was there anything else needed to resolve this?
