### ISSUE TITLE
Adding series to XYChart without axes results in infinite loop

### ISSUE THREAD

**Issue by ailon** [amcharts/amcharts4#963]
When you create a chart with code like this:

```js
// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart);

// Create series
var series = chart.series.push(new am4charts.ColumnSeries());
```

it results in an infinite loop with `Error: "There are no X axes on chart.` spewed into the console on repeat indefinitely.

**Comment by martynasma** [comment]
Fixed in [4.1.8](https://github.com/amcharts/amcharts4/releases/tag/4.1.8).

## [4.1.8] - 2019-02-15

### Added
- JSON: You can now specify both list of items and template settings for `ListTemplate`, e.g.: `titles: { template: { ... }, values: [{ ... }] }`. Specifying it the old way will still work.

### Changed
- `DateAxis` will now pay attention to `dateFormatter.firstDayOfWeek` when grid is in "weekly" mode.

### Fixed
- Using `proprtyFields` on a `LineSeries` sometimes could result in an error. (fix by @AndiLi99)
- French locale (fr_FR) updated for correct decimal/thousands separators.
- Export: `scale` in image export options was being ignored.
- JSON: `cursor.snapToSeries` was not working in JSON configs.
- Selection was acting funky when zooming `DateAxis` and cursor moved out of plot area.
- An infinite error message loop fixed which was happening if series was added and there was no X or Y axes defined.
- Tooltip on the last available data item was left visible even if cursor moved to the date where the series had no data points.
- When `snapToSeries` was enabled in `XYCursor`, vertical line was not shown.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by danilotorrisi** [comment]
It looks like this bug is still there. If I try to create a chart:

`
const chart = container.createChild(am4charts.XYChart)
const series = chart.series.push(new am4charts.ColumnSeries());
`

An infinite loop still appear, is there some kind of regression or another bug?
